// src/lib/components/panel/options-panel.tsx
import type { ReactNode } from 'react';

import { CollapsibleAside } from '@/lib/components/ui/collapsible-aside';

interface OptionsPanelProps {
	readonly title?: string;
	readonly width?: string;
	readonly show?: boolean;
	readonly defaultShow?: boolean;
	readonly onShowChange?: (show: boolean) => void;
	readonly onClose?: () => void;
	readonly onOpen?: () => void;
	readonly children?: ReactNode;
}

export function OptionsPanel({
	title = 'Options',
	width = 'w-[var(--rail-w)]',
	show,
	defaultShow = true,
	onShowChange,
	onClose,
	onOpen,
	children,
}: OptionsPanelProps) {
	return (
		<CollapsibleAside
			show={show}
			defaultShow={defaultShow}
			onShowChange={onShowChange}
			title={title}
			background="bg-surface-2"
			width={width}
			onClose={onClose}
			onOpen={onOpen}
		>
			{children}
		</CollapsibleAside>
	);
}

export type { OptionsPanelProps };

// src/lib/components/panel/options-panel.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import { CollapsibleAside } from '$lib/components/ui/collapsible-aside';

	interface Props {
		title?: string;
		width?: string;
		show?: boolean;
		onclose?: () => void;
		onopen?: () => void;
		children?: Snippet;
	}

	let {
		title = 'Options',
		width = 'w-[var(--rail-w)]',
		show = $bindable(true),
		onclose,
		onopen,
		children,
	}: Props = $props();
</script>

<CollapsibleAside bind:show {title} background="bg-surface-2" {width} {onclose} {onopen}>
	{@render children?.()}
</CollapsibleAside>
