// src/routes/base64-encoder.tsx
import { createFileRoute } from '@tanstack/react-router';
import { useEffect, useState } from 'react';
import { Code2 } from 'lucide-react';
import { toast } from 'sonner';

import { CodeEditor } from '@/lib/components/editor';
import {
	FormCheckbox,
	FormCheckboxGroup,
	FormInfo,
	FormMode,
	FormSection,
	FormSelect,
} from '@/lib/components/form';
import { SectionHeader, SplitPane } from '@/lib/components/layout';
import { ToolShell } from '@/lib/components/shell';
import { EmbeddedEmptyState, StatItem } from '@/lib/components/status';
import {
	BASE64_MIME_TYPES,
	type Base64DecodeOptions,
	type Base64EncodeOptions,
	type Base64LineBreak,
	type Base64Variant,
	calculateBase64Stats,
	decodeFromBase64,
	defaultBase64DecodeOptions,
	defaultBase64EncodeOptions,
	detectBase64Variant,
	encodeToBase64,
	extractMimeType,
	isDataUrl,
	SAMPLE_TEXT_FOR_BASE64,
} from '@/lib/services/encoders';

type Mode = 'encode' | 'decode';

export const Route = createFileRoute('/base64-encoder')({
	component: Base64EncoderPage,
});

function Base64EncoderPage() {
	const [mode, setMode] = useState<Mode>('encode');
	const [input, setInput] = useState('');
	const [showOptions, setShowOptions] = useState(true);

	const [variant, setVariant] = useState<Base64Variant>(defaultBase64EncodeOptions.variant);
	const [padding, setPadding] = useState(defaultBase64EncodeOptions.padding);
	const [lineBreak, setLineBreak] = useState<Base64LineBreak>(defaultBase64EncodeOptions.lineBreak);
	const [dataUrl, setDataUrl] = useState(defaultBase64EncodeOptions.dataUrl);
	const [mimeType, setMimeType] = useState(defaultBase64EncodeOptions.mimeType);

	const [ignoreWhitespace, setIgnoreWhitespace] = useState(
		defaultBase64DecodeOptions.ignoreWhitespace
	);
	const [ignoreInvalidChars, setIgnoreInvalidChars] = useState(
		defaultBase64DecodeOptions.ignoreInvalidChars
	);
	const [autoDetectVariant, setAutoDetectVariant] = useState(
		defaultBase64DecodeOptions.autoDetectVariant
	);

	useEffect(() => {
		document.title = 'Base64 Encoder — Kogu';
	}, []);

	const encodeOptions: Partial<Base64EncodeOptions> = {
		variant,
		padding,
		lineBreak,
		dataUrl,
		mimeType,
	};

	const decodeOptions: Partial<Base64DecodeOptions> = {
		ignoreWhitespace,
		ignoreInvalidChars,
		autoDetectVariant,
	};

	const detectedVariant = mode === 'decode' && input.trim() ? detectBase64Variant(input) : null;
	const detectedDataUrl = mode === 'decode' && input.trim() ? isDataUrl(input) : false;
	const detectedMimeType = detectedDataUrl ? extractMimeType(input) : null;

	const { output, error } = ((): { output: string; error: string } => {
		if (!input.trim()) return { output: '', error: '' };
		try {
			const result =
				mode === 'encode'
					? encodeToBase64(input, encodeOptions)
					: decodeFromBase64(input, decodeOptions);
			return { output: result, error: '' };
		} catch (e) {
			return { output: '', error: e instanceof Error ? e.message : 'Invalid input' };
		}
	})();

	const stats =
		input.trim() && output
			? mode === 'encode'
				? calculateBase64Stats(input, output)
				: calculateBase64Stats(output, input)
			: null;

	const valid: boolean | null = !input.trim() ? null : !error;

	const handlePaste = async () => {
		try {
			const text = await navigator.clipboard.readText();
			if (text) setInput(text);
		} catch {
			// Clipboard access denied
		}
	};

	const handleClear = () => setInput('');

	const handleCopy = async () => {
		try {
			await navigator.clipboard.writeText(output);
			toast.success('Copied to clipboard');
		} catch {
			toast.error('Failed to copy to clipboard');
		}
	};

	const handleSample = () => setInput(SAMPLE_TEXT_FOR_BASE64);

	const handleModeChange = (newMode: Mode) => {
		setMode(newMode);
		setInput('');
	};

	return (
		<ToolShell
			valid={valid}
			error={error || undefined}
			showRail={showOptions}
			onShowRailChange={setShowOptions}
			statusContent={
				stats ? (
					<>
						<StatItem
							label="Input"
							value={`${stats.inputChars} chars (${stats.inputBytes} bytes)`}
						/>
						<StatItem label="Output" value={`${stats.outputChars} chars`} />
						<StatItem label="Ratio" value={stats.ratio} />
					</>
				) : null
			}
			rail={
				<>
					<FormSection title="Mode">
						<FormMode
							value={mode}
							onValueChange={handleModeChange}
							options={[
								{ value: 'encode', label: 'Encode' },
								{ value: 'decode', label: 'Decode' },
							]}
						/>
					</FormSection>

					{mode === 'encode' ? (
						<>
							<FormSection title="Encoding">
								<FormSelect
									label="Variant"
									value={variant}
									onValueChange={(v) => setVariant(v as Base64Variant)}
									options={[
										{
											value: 'standard',
											label: 'Standard',
											description: 'Uses + and / (RFC 4648 §4)',
										},
										{
											value: 'url-safe',
											label: 'URL-safe',
											description: 'Uses - and _ (RFC 4648 §5)',
										},
									]}
								/>
								<FormSelect
									label="Line Break"
									value={lineBreak}
									onValueChange={(v) => setLineBreak(v as Base64LineBreak)}
									options={[
										{ value: 'none', label: 'None', description: 'Single continuous line' },
										{ value: '64', label: '64 chars', description: 'PEM convention' },
										{ value: '76', label: '76 chars', description: 'MIME / RFC 2045' },
									]}
								/>
								<div className="pt-1">
									<FormCheckbox
										label="Include padding (=)"
										checked={padding}
										onCheckedChange={setPadding}
									/>
								</div>
							</FormSection>

							<FormSection title="Data URL">
								<FormCheckbox
									label="Output as Data URL"
									checked={dataUrl}
									onCheckedChange={setDataUrl}
								/>
								{dataUrl ? (
									<div className="pt-1">
										<FormSelect
											label="MIME Type"
											value={mimeType}
											onValueChange={setMimeType}
											options={[...BASE64_MIME_TYPES]}
										/>
									</div>
								) : null}
							</FormSection>

							<FormSection title="Info" open={false}>
								<FormInfo title="Standard vs URL-safe">
									<p>
										<strong>Standard:</strong> Uses <code>+</code> and <code>/</code> characters.
									</p>
									<p className="mt-1">
										<strong>URL-safe:</strong> Uses <code>-</code> and <code>_</code> instead, safe
										for URLs and filenames.
									</p>
								</FormInfo>
							</FormSection>
						</>
					) : (
						<>
							<FormSection title="Decoding">
								<FormCheckboxGroup>
									<FormCheckbox
										label="Ignore whitespace"
										checked={ignoreWhitespace}
										onCheckedChange={setIgnoreWhitespace}
									/>
									<FormCheckbox
										label="Ignore invalid characters"
										checked={ignoreInvalidChars}
										onCheckedChange={setIgnoreInvalidChars}
									/>
									<FormCheckbox
										label="Auto-detect URL-safe variant"
										checked={autoDetectVariant}
										onCheckedChange={setAutoDetectVariant}
									/>
								</FormCheckboxGroup>
							</FormSection>

							{detectedVariant || detectedDataUrl ? (
								<FormSection title="Detected">
									<FormInfo showIcon={false}>
										{detectedVariant ? (
											<p>
												<strong>Variant:</strong>{' '}
												{detectedVariant === 'url-safe' ? 'URL-safe (-_)' : 'Standard (+/)'}
											</p>
										) : null}
										{detectedDataUrl ? (
											<>
												<p className="mt-1">
													<strong>Format:</strong> Data URL
												</p>
												{detectedMimeType ? (
													<p className="mt-1">
														<strong>MIME:</strong> {detectedMimeType}
													</p>
												) : null}
											</>
										) : null}
									</FormInfo>
								</FormSection>
							) : null}
						</>
					)}
				</>
			}
		>
			<SplitPane
				className="h-full flex-1"
				left={
					<CodeEditor
						title={mode === 'encode' ? 'Text Input' : 'Base64 Input'}
						value={input}
						onChange={setInput}
						mode="input"
						editorMode="plain"
						placeholder={
							mode === 'encode' ? 'Enter text to encode...' : 'Enter Base64 to decode...'
						}
						onSample={handleSample}
						onPaste={handlePaste}
						onClear={handleClear}
						showViewToggle={false}
					/>
				}
				right={
					!input.trim() ? (
						<div className="flex h-full flex-col overflow-hidden">
							<SectionHeader title={mode === 'encode' ? 'Base64 Output' : 'Decoded Text'} />
							<div className="flex-1">
								<EmbeddedEmptyState
									icon={Code2}
									title={mode === 'encode' ? 'Enter text to encode' : 'Paste Base64 to decode'}
									description={
										mode === 'encode'
											? 'The Base64-encoded result will appear here.'
											: 'The decoded plain text will appear here.'
									}
									fillHeight
								/>
							</div>
						</div>
					) : (
						<CodeEditor
							title={mode === 'encode' ? 'Base64 Output' : 'Decoded Text'}
							value={output}
							mode="readonly"
							editorMode="plain"
							placeholder={mode === 'encode' ? 'Encoded output...' : 'Decoded output...'}
							onCopy={handleCopy}
							showViewToggle={false}
						/>
					)
				}
			/>
		</ToolShell>
	);
}

// src/routes/base64-encoder/+page.svelte
<script lang="ts">
	import { Code2 } from '@lucide/svelte';
	import { CodeEditor } from '$lib/components/editor';
	import {
		FormCheckbox,
		FormCheckboxGroup,
		FormInfo,
		FormMode,
		FormSection,
		FormSelect,
	} from '$lib/components/form';
	import { SectionHeader, SplitPane } from '$lib/components/layout';
	import { ToolShell } from '$lib/components/shell';
	import { EmbeddedEmptyState, StatItem } from '$lib/components/status';
	import {
		BASE64_MIME_TYPES,
		type Base64DecodeOptions,
		type Base64EncodeOptions,
		type Base64LineBreak,
		type Base64Stats,
		type Base64Variant,
		calculateBase64Stats,
		decodeFromBase64,
		defaultBase64DecodeOptions,
		defaultBase64EncodeOptions,
		detectBase64Variant,
		encodeToBase64,
		extractMimeType,
		isDataUrl,
		SAMPLE_TEXT_FOR_BASE64,
	} from '$lib/services/encoders.js';

	type Mode = 'encode' | 'decode';

	// State
	let mode = $state<Mode>('encode');
	let input = $state('');
	let showOptions = $state(true);

	// Encode options
	let variant = $state<Base64Variant>(defaultBase64EncodeOptions.variant);
	let padding = $state(defaultBase64EncodeOptions.padding);
	let lineBreak = $state<Base64LineBreak>(defaultBase64EncodeOptions.lineBreak);
	let dataUrl = $state(defaultBase64EncodeOptions.dataUrl);
	let mimeType = $state(defaultBase64EncodeOptions.mimeType);

	// Decode options
	let ignoreWhitespace = $state(defaultBase64DecodeOptions.ignoreWhitespace);
	let ignoreInvalidChars = $state(defaultBase64DecodeOptions.ignoreInvalidChars);
	let autoDetectVariant = $state(defaultBase64DecodeOptions.autoDetectVariant);

	// Derived encode options object
	const encodeOptions = $derived<Partial<Base64EncodeOptions>>({
		variant,
		padding,
		lineBreak,
		dataUrl,
		mimeType,
	});

	// Derived decode options object
	const decodeOptions = $derived<Partial<Base64DecodeOptions>>({
		ignoreWhitespace,
		ignoreInvalidChars,
		autoDetectVariant,
	});

	// Detected info for decode mode
	const detectedVariant = $derived(
		mode === 'decode' && input.trim() ? detectBase64Variant(input) : null
	);
	const detectedDataUrl = $derived(mode === 'decode' && input.trim() ? isDataUrl(input) : false);
	const detectedMimeType = $derived(detectedDataUrl ? extractMimeType(input) : null);

	// Computed output and error
	const encodeResult = $derived.by((): { output: string; error: string } => {
		if (!input.trim()) {
			return { output: '', error: '' };
		}

		try {
			const result =
				mode === 'encode'
					? encodeToBase64(input, encodeOptions)
					: decodeFromBase64(input, decodeOptions);
			return { output: result, error: '' };
		} catch (e) {
			return { output: '', error: e instanceof Error ? e.message : 'Invalid input' };
		}
	});

	// Derived values from result
	const output = $derived(encodeResult.output);
	const error = $derived(encodeResult.error);

	// Stats calculation
	const stats = $derived.by((): Base64Stats | null => {
		if (!input.trim() || !output) return null;
		return mode === 'encode'
			? calculateBase64Stats(input, output)
			: calculateBase64Stats(output, input);
	});

	// Validation state
	const valid = $derived.by((): boolean | null => {
		if (!input.trim()) return null;
		return !error;
	});

	// Handlers
	const handlePaste = async () => {
		try {
			const text = await navigator.clipboard.readText();
			if (text) input = text;
		} catch {
			// Clipboard access denied
		}
	};

	const handleClear = () => {
		input = '';
	};

	const handleCopy = async () => {
		try {
			await navigator.clipboard.writeText(output);
		} catch {
			// Clipboard access denied
		}
	};

	const handleSample = () => {
		input = SAMPLE_TEXT_FOR_BASE64;
	};

	const handleModeChange = (newMode: string) => {
		mode = newMode as Mode;
		input = '';
	};
</script>

<svelte:head>
	<title>Base64 Encoder - Kogu</title>
</svelte:head>

<ToolShell {valid} {error} bind:showRail={showOptions}>
	{#snippet statusContent()}
		{#if stats}
			<StatItem label="Input" value="{stats.inputChars} chars ({stats.inputBytes} bytes)" />
			<StatItem label="Output" value="{stats.outputChars} chars" />
			<StatItem label="Ratio" value={stats.ratio} />
		{/if}
	{/snippet}

	{#snippet rail()}
		<FormSection title="Mode">
			<FormMode
				value={mode}
				onchange={handleModeChange}
				options={[
					{ value: 'encode', label: 'Encode' },
					{ value: 'decode', label: 'Decode' },
				]}
			/>
		</FormSection>

		{#if mode === 'encode'}
			<FormSection title="Encoding">
				<FormSelect
					label="Variant"
					bind:value={variant}
					options={[
						{
							value: 'standard',
							label: 'Standard',
							description: 'Uses + and / (RFC 4648 §4)',
						},
						{
							value: 'url-safe',
							label: 'URL-safe',
							description: 'Uses - and _ (RFC 4648 §5)',
						},
					]}
				/>
				<FormSelect
					label="Line Break"
					bind:value={lineBreak}
					options={[
						{ value: 'none', label: 'None', description: 'Single continuous line' },
						{ value: '64', label: '64 chars', description: 'PEM convention' },
						{ value: '76', label: '76 chars', description: 'MIME / RFC 2045' },
					]}
				/>
				<div class="pt-1">
					<FormCheckbox label="Include padding (=)" bind:checked={padding} />
				</div>
			</FormSection>

			<FormSection title="Data URL">
				<FormCheckbox label="Output as Data URL" bind:checked={dataUrl} />
				{#if dataUrl}
					<div class="pt-1">
						<FormSelect label="MIME Type" bind:value={mimeType} options={[...BASE64_MIME_TYPES]} />
					</div>
				{/if}
			</FormSection>

			<FormSection title="Info" open={false}>
				<FormInfo title="Standard vs URL-safe">
					<p><strong>Standard:</strong> Uses <code>+</code> and <code>/</code> characters.</p>
					<p class="mt-1">
						<strong>URL-safe:</strong> Uses <code>-</code> and <code>_</code> instead, safe for URLs and
						filenames.
					</p>
				</FormInfo>
			</FormSection>
		{:else}
			<FormSection title="Decoding">
				<FormCheckboxGroup>
					<FormCheckbox label="Ignore whitespace" bind:checked={ignoreWhitespace} />
					<FormCheckbox label="Ignore invalid characters" bind:checked={ignoreInvalidChars} />
					<FormCheckbox label="Auto-detect URL-safe variant" bind:checked={autoDetectVariant} />
				</FormCheckboxGroup>
			</FormSection>

			{#if detectedVariant || detectedDataUrl}
				<FormSection title="Detected">
					<FormInfo showIcon={false}>
						{#if detectedVariant}
							<p>
								<strong>Variant:</strong>
								{detectedVariant === 'url-safe' ? 'URL-safe (-_)' : 'Standard (+/)'}
							</p>
						{/if}
						{#if detectedDataUrl}
							<p class="mt-1"><strong>Format:</strong> Data URL</p>
							{#if detectedMimeType}
								<p class="mt-1"><strong>MIME:</strong> {detectedMimeType}</p>
							{/if}
						{/if}
					</FormInfo>
				</FormSection>
			{/if}
		{/if}
	{/snippet}

	<SplitPane class="h-full flex-1">
		{#snippet left()}
			<CodeEditor
				title={mode === 'encode' ? 'Text Input' : 'Base64 Input'}
				value={input}
				onchange={(v) => (input = v)}
				mode="input"
				editorMode="plain"
				placeholder={mode === 'encode' ? 'Enter text to encode...' : 'Enter Base64 to decode...'}
				onsample={handleSample}
				onpaste={handlePaste}
				onclear={handleClear}
				showViewToggle={false}
			/>
		{/snippet}
		{#snippet right()}
			{#if !input.trim()}
				<div class="flex h-full flex-col overflow-hidden">
					<SectionHeader title={mode === 'encode' ? 'Base64 Output' : 'Decoded Text'} />
					<div class="flex-1">
						<EmbeddedEmptyState
							icon={Code2}
							title={mode === 'encode' ? 'Enter text to encode' : 'Paste Base64 to decode'}
							description={mode === 'encode'
								? 'The Base64-encoded result will appear here.'
								: 'The decoded plain text will appear here.'}
							fillHeight
						/>
					</div>
				</div>
			{:else}
				<CodeEditor
					title={mode === 'encode' ? 'Base64 Output' : 'Decoded Text'}
					value={output}
					mode="readonly"
					editorMode="plain"
					placeholder={mode === 'encode' ? 'Encoded output...' : 'Decoded output...'}
					oncopy={handleCopy}
					showViewToggle={false}
				/>
			{/if}
		{/snippet}
	</SplitPane>
</ToolShell>
