// src/routes/yaml-formatter/tabs/convert-tab.svelte
<script lang="ts">
	import * as yaml from 'yaml';
	import {
		FormCheckbox,
		FormCheckboxGroup,
		FormInput,
		FormMode,
		FormSection,
		FormSelect,
	} from '$lib/components/form';
	import { ConvertTab } from '$lib/components/template';
	import {
		type YamlToJsonOptions,
		type YamlToXmlOptions,
		yamlToJson,
		yamlToXml,
	} from '$lib/services/formatters';
	import { copyToClipboard, downloadTextFile, pasteFromClipboard } from '../utils.js';

	interface Props {
		input: string;
		onInputChange: (value: string) => void;
		onStatsChange?: (stats: { input: string; valid: boolean | null; error: string }) => void;
	}

	let { input, onInputChange, onStatsChange }: Props = $props();

	// Output format
	let convertFormat = $state<'json' | 'xml'>('json');

	// JSON options
	let jsonIndentStr = $state('2');
	let jsonSortKeys = $state(false);

	// XML options - Structure
	let xmlRootName = $state('root');
	let xmlArrayItemName = $state('item');
	let xmlAttributePrefix = $state('@');

	// XML options - Formatting
	let xmlIndentStr = $state('2');
	let xmlIndentType = $state<'spaces' | 'tabs'>('spaces');
	let xmlLineSeparator = $state<'\n' | '\r\n'>('\n');
	let xmlCollapseContent = $state(false);

	// XML options - Declaration
	let xmlDeclaration = $state(true);
	let xmlDeclarationVersion = $state('1.0');
	let xmlDeclarationEncoding = $state('UTF-8');

	// XML options - Tags
	let xmlSelfClosing = $state(true);
	let xmlWhiteSpaceAtEndOfSelfclosingTag = $state(false);

	// XML options - Content
	let xmlCdata = $state(false);
	let xmlCdataThresholdStr = $state('0');
	let xmlEscapeText = $state(true);
	let xmlSortAttributes = $state(false);
	let xmlSortKeys = $state(false);

	// XML options - Comments
	let xmlHeaderComment = $state('');

	// Derived values
	const jsonIndent = $derived(Number.parseInt(jsonIndentStr, 10) || 2);
	const xmlIndent = $derived(Number.parseInt(xmlIndentStr, 10) || 2);
	const xmlCdataThreshold = $derived(Number.parseInt(xmlCdataThresholdStr, 10) || 0);

	// JSON options object
	const jsonOptions = $derived<YamlToJsonOptions>({
		indent: jsonIndent,
		sortKeys: jsonSortKeys,
	});

	// XML options object
	const xmlOptions = $derived<YamlToXmlOptions>({
		// Structure
		rootName: xmlRootName,
		arrayItemName: xmlArrayItemName,
		attributePrefix: xmlAttributePrefix,
		// Formatting
		indent: xmlIndent,
		indentType: xmlIndentType,
		lineSeparator: xmlLineSeparator,
		collapseContent: xmlCollapseContent,
		// Declaration
		declaration: xmlDeclaration,
		declarationVersion: xmlDeclarationVersion,
		declarationEncoding: xmlDeclarationEncoding,
		// Tags
		selfClosing: xmlSelfClosing,
		whiteSpaceAtEndOfSelfclosingTag: xmlWhiteSpaceAtEndOfSelfclosingTag,
		// Content
		cdata: xmlCdata,
		cdataThreshold: xmlCdataThreshold,
		escapeText: xmlEscapeText,
		sortAttributes: xmlSortAttributes,
		sortKeys: xmlSortKeys,
		// Comments
		headerComment: xmlHeaderComment || undefined,
	});

	// Validation function
	const validate = (input: string) => {
		if (!input.trim()) return { valid: null as boolean | null };
		try {
			yaml.parse(input);
			return { valid: true };
		} catch {
			return { valid: false };
		}
	};

	// Conversion function
	const convert = (input: string) => {
		try {
			const output =
				convertFormat === 'json' ? yamlToJson(input, jsonOptions) : yamlToXml(input, xmlOptions);
			return { output, error: '' };
		} catch (e) {
			return { output: '', error: e instanceof Error ? e.message : 'Conversion failed' };
		}
	};

	// Output editor mode based on format
	const outputEditorMode = $derived(convertFormat === 'json' ? 'json' : 'xml');
	const downloadFilename = $derived(`converted.${convertFormat}`);
	const outputTitle = $derived(`Output (${convertFormat.toUpperCase()})`);
</script>

<ConvertTab
	inputEditorMode="yaml"
	{outputEditorMode}
	{input}
	{onInputChange}
	placeholder="Enter YAML here..."
	{validate}
	{convert}
	{onStatsChange}
	{downloadFilename}
	{outputTitle}
	{copyToClipboard}
	{pasteFromClipboard}
	{downloadTextFile}
>
	{#snippet options()}
		<FormSection title="Output Format">
			<FormMode
				bind:value={convertFormat}
				options={[
					{ value: 'json', label: 'JSON' },
					{ value: 'xml', label: 'XML' },
				]}
			/>
		</FormSection>

		{#if convertFormat === 'json'}
			<FormSection title="Formatting">
				<FormSelect
					label="Indent"
					bind:value={jsonIndentStr}
					options={[
						{ value: '0', label: 'None' },
						{ value: '2', label: '2' },
						{ value: '4', label: '4' },
						{ value: '8', label: '8' },
					]}
				/>
			</FormSection>

			<FormSection title="Keys">
				<FormCheckbox label="Sort keys alphabetically" bind:checked={jsonSortKeys} />
			</FormSection>
		{/if}

		{#if convertFormat === 'xml'}
			<FormSection title="Structure">
				<div class="grid grid-cols-2 gap-2">
					<FormInput
						label="Root Element"
						bind:value={xmlRootName}
						placeholder="root"
						size="compact"
					/>
					<FormInput
						label="Array Item"
						bind:value={xmlArrayItemName}
						placeholder="item"
						size="compact"
					/>
				</div>
				<FormInput
					label="Attribute Prefix"
					bind:value={xmlAttributePrefix}
					placeholder="@"
					size="compact"
					class="font-mono"
				/>
			</FormSection>

			<FormSection title="Formatting">
				<div class="grid grid-cols-2 gap-2">
					<FormSelect
						label="Indent"
						bind:value={xmlIndentStr}
						options={[
							{ value: '0', label: 'None' },
							{ value: '2', label: '2' },
							{ value: '4', label: '4' },
							{ value: '8', label: '8' },
						]}
					/>
					<FormSelect
						label="Indent Type"
						bind:value={xmlIndentType}
						options={[
							{ value: 'spaces', label: 'Spaces' },
							{ value: 'tabs', label: 'Tabs' },
						]}
					/>
				</div>
				<FormSelect
					label="Line Separator"
					bind:value={xmlLineSeparator}
					options={[
						{ value: '\n', label: 'LF (Unix)' },
						{ value: '\r\n', label: 'CRLF (Windows)' },
					]}
				/>
				<FormCheckboxGroup class="pt-1">
					<FormCheckbox label="Collapse content on single line" bind:checked={xmlCollapseContent} />
				</FormCheckboxGroup>
			</FormSection>

			<FormSection title="Declaration">
				<FormCheckbox label="Include XML declaration" bind:checked={xmlDeclaration} />
				{#if xmlDeclaration}
					<div class="grid grid-cols-2 gap-2 pt-1">
						<FormInput
							label="Version"
							bind:value={xmlDeclarationVersion}
							placeholder="1.0"
							size="compact"
							class="font-mono"
						/>
						<FormInput
							label="Encoding"
							bind:value={xmlDeclarationEncoding}
							placeholder="UTF-8"
							size="compact"
							class="font-mono"
						/>
					</div>
				{/if}
			</FormSection>

			<FormSection title="Tags">
				<FormCheckbox label="Use self-closing tags" bind:checked={xmlSelfClosing} />
				<FormCheckbox
					label="Space before self-closing />"
					bind:checked={xmlWhiteSpaceAtEndOfSelfclosingTag}
				/>
			</FormSection>

			<FormSection title="Content">
				<FormCheckbox label="Wrap text in CDATA" bind:checked={xmlCdata} />
				{#if xmlCdata}
					<div class="pt-1">
						<FormInput
							label="CDATA Threshold (chars)"
							bind:value={xmlCdataThresholdStr}
							placeholder="0"
							size="compact"
							class="font-mono"
							hint="0 = always use CDATA"
						/>
					</div>
				{/if}
				<FormCheckbox label="Escape special characters" bind:checked={xmlEscapeText} />
			</FormSection>

			<FormSection title="Sorting">
				<FormCheckbox label="Sort element keys" bind:checked={xmlSortKeys} />
				<FormCheckbox label="Sort attributes" bind:checked={xmlSortAttributes} />
			</FormSection>

			<FormSection title="Comments">
				<FormInput
					label="Header Comment"
					bind:value={xmlHeaderComment}
					placeholder="Optional comment..."
					size="compact"
				/>
			</FormSection>
		{/if}
	{/snippet}
</ConvertTab>

// src/lib/components/formatter-tabs/yaml/convert-tab.tsx
import { useCallback, useState } from 'react';
import * as yaml from 'yaml';

import {
	FormCheckbox,
	FormCheckboxGroup,
	FormInput,
	FormMode,
	FormSection,
	FormSelect,
} from '@/lib/components/form';
import { ConvertTab as ConvertTabTemplate } from '@/lib/components/template';
import {
	type YamlToJsonOptions,
	type YamlToXmlOptions,
	yamlToJson,
	yamlToXml,
} from '@/lib/services/formatters';
import { copyToClipboard, pasteFromClipboard } from '@/lib/utils/file-operations';

type ConvertFormat = 'json' | 'xml';
type XmlIndentType = 'spaces' | 'tabs';
type XmlLineSeparator = '\n' | '\r\n';

interface TabStats {
	readonly input: string;
	readonly valid: boolean | null;
	readonly error: string;
}

interface ConvertTabProps {
	readonly input: string;
	readonly onInputChange: (value: string) => void;
	readonly onStatsChange?: (stats: TabStats) => void;
}

export function ConvertTab({ input, onInputChange, onStatsChange }: ConvertTabProps) {
	const [convertFormat, setConvertFormat] = useState<ConvertFormat>('json');

	// JSON options.
	const [jsonIndentStr, setJsonIndentStr] = useState<string>('2');
	const [jsonSortKeys, setJsonSortKeys] = useState<boolean>(false);

	// XML options - Structure.
	const [xmlRootName, setXmlRootName] = useState<string>('root');
	const [xmlArrayItemName, setXmlArrayItemName] = useState<string>('item');
	const [xmlAttributePrefix, setXmlAttributePrefix] = useState<string>('@');

	// XML options - Formatting.
	const [xmlIndentStr, setXmlIndentStr] = useState<string>('2');
	const [xmlIndentType, setXmlIndentType] = useState<XmlIndentType>('spaces');
	const [xmlLineSeparator, setXmlLineSeparator] = useState<XmlLineSeparator>('\n');
	const [xmlCollapseContent, setXmlCollapseContent] = useState<boolean>(false);

	// XML options - Declaration.
	const [xmlDeclaration, setXmlDeclaration] = useState<boolean>(true);
	const [xmlDeclarationVersion, setXmlDeclarationVersion] = useState<string>('1.0');
	const [xmlDeclarationEncoding, setXmlDeclarationEncoding] = useState<string>('UTF-8');

	// XML options - Tags.
	const [xmlSelfClosing, setXmlSelfClosing] = useState<boolean>(true);
	const [xmlWhiteSpaceAtEndOfSelfclosingTag, setXmlWhiteSpaceAtEndOfSelfclosingTag] =
		useState<boolean>(false);

	// XML options - Content.
	const [xmlCdata, setXmlCdata] = useState<boolean>(false);
	const [xmlCdataThresholdStr, setXmlCdataThresholdStr] = useState<string>('0');
	const [xmlEscapeText, setXmlEscapeText] = useState<boolean>(true);
	const [xmlSortAttributes, setXmlSortAttributes] = useState<boolean>(false);
	const [xmlSortKeys, setXmlSortKeys] = useState<boolean>(false);

	// XML options - Comments.
	const [xmlHeaderComment, setXmlHeaderComment] = useState<string>('');

	const jsonIndent = Number.parseInt(jsonIndentStr, 10) || 2;
	const xmlIndent = Number.parseInt(xmlIndentStr, 10) || 2;
	const xmlCdataThreshold = Number.parseInt(xmlCdataThresholdStr, 10) || 0;

	const jsonOptions: YamlToJsonOptions = {
		indent: jsonIndent,
		sortKeys: jsonSortKeys,
	};

	const xmlOptions: YamlToXmlOptions = {
		// Structure.
		rootName: xmlRootName,
		arrayItemName: xmlArrayItemName,
		attributePrefix: xmlAttributePrefix,
		// Formatting.
		indent: xmlIndent,
		indentType: xmlIndentType,
		lineSeparator: xmlLineSeparator,
		collapseContent: xmlCollapseContent,
		// Declaration.
		declaration: xmlDeclaration,
		declarationVersion: xmlDeclarationVersion,
		declarationEncoding: xmlDeclarationEncoding,
		// Tags.
		selfClosing: xmlSelfClosing,
		whiteSpaceAtEndOfSelfclosingTag: xmlWhiteSpaceAtEndOfSelfclosingTag,
		// Content.
		cdata: xmlCdata,
		cdataThreshold: xmlCdataThreshold,
		escapeText: xmlEscapeText,
		sortAttributes: xmlSortAttributes,
		sortKeys: xmlSortKeys,
		// Comments.
		headerComment: xmlHeaderComment || undefined,
	};

	const validate = useCallback((value: string): { valid: boolean | null } => {
		if (!value.trim()) return { valid: null };
		try {
			yaml.parse(value);
			return { valid: true };
		} catch {
			return { valid: false };
		}
	}, []);

	const convert = useCallback(
		(value: string): { output: string; error: string } => {
			try {
				const result =
					convertFormat === 'json' ? yamlToJson(value, jsonOptions) : yamlToXml(value, xmlOptions);
				return { output: result, error: '' };
			} catch (e) {
				return { output: '', error: e instanceof Error ? e.message : 'Conversion failed' };
			}
		},
		[convertFormat, jsonOptions, xmlOptions]
	);

	const outputEditorMode = convertFormat === 'json' ? 'json' : 'xml';
	const outputTitle = `Output (${convertFormat.toUpperCase()})`;

	const handleCopyAdapter = (text: string): void => {
		copyToClipboard(text).catch(() => {
			// Clipboard write failed; ignore.
		});
	};

	return (
		<ConvertTabTemplate
			inputEditorMode="yaml"
			outputEditorMode={outputEditorMode}
			input={input}
			onInputChange={onInputChange}
			placeholder="Enter YAML here..."
			validate={validate}
			convert={convert}
			onStatsChange={onStatsChange}
			outputTitle={outputTitle}
			copyToClipboard={handleCopyAdapter}
			pasteFromClipboard={pasteFromClipboard}
			renderOptions={() => (
				<>
					<FormSection title="Output Format">
						<FormMode
							value={convertFormat}
							onValueChange={setConvertFormat}
							options={[
								{ value: 'json', label: 'JSON' },
								{ value: 'xml', label: 'XML' },
							]}
						/>
					</FormSection>

					{convertFormat === 'json' ? (
						<>
							<FormSection title="Formatting">
								<FormSelect
									label="Indent"
									value={jsonIndentStr}
									onValueChange={setJsonIndentStr}
									options={[
										{ value: '0', label: 'None' },
										{ value: '2', label: '2' },
										{ value: '4', label: '4' },
										{ value: '8', label: '8' },
									]}
								/>
							</FormSection>

							<FormSection title="Keys">
								<FormCheckbox
									label="Sort keys alphabetically"
									checked={jsonSortKeys}
									onCheckedChange={setJsonSortKeys}
								/>
							</FormSection>
						</>
					) : null}

					{convertFormat === 'xml' ? (
						<>
							<FormSection title="Structure">
								<div className="grid grid-cols-2 gap-2">
									<FormInput
										label="Root Element"
										value={xmlRootName}
										onValueChange={setXmlRootName}
										placeholder="root"
										size="compact"
									/>
									<FormInput
										label="Array Item"
										value={xmlArrayItemName}
										onValueChange={setXmlArrayItemName}
										placeholder="item"
										size="compact"
									/>
								</div>
								<FormInput
									label="Attribute Prefix"
									value={xmlAttributePrefix}
									onValueChange={setXmlAttributePrefix}
									placeholder="@"
									size="compact"
									className="font-mono"
								/>
							</FormSection>

							<FormSection title="Formatting">
								<div className="grid grid-cols-2 gap-2">
									<FormSelect
										label="Indent"
										value={xmlIndentStr}
										onValueChange={setXmlIndentStr}
										options={[
											{ value: '0', label: 'None' },
											{ value: '2', label: '2' },
											{ value: '4', label: '4' },
											{ value: '8', label: '8' },
										]}
									/>
									<FormSelect
										label="Indent Type"
										value={xmlIndentType}
										onValueChange={(v) => setXmlIndentType(v as XmlIndentType)}
										options={[
											{ value: 'spaces', label: 'Spaces' },
											{ value: 'tabs', label: 'Tabs' },
										]}
									/>
								</div>
								<FormSelect
									label="Line Separator"
									value={xmlLineSeparator}
									onValueChange={(v) => setXmlLineSeparator(v as XmlLineSeparator)}
									options={[
										{ value: '\n', label: 'LF (Unix)' },
										{ value: '\r\n', label: 'CRLF (Windows)' },
									]}
								/>
								<FormCheckboxGroup className="pt-1">
									<FormCheckbox
										label="Collapse content on single line"
										checked={xmlCollapseContent}
										onCheckedChange={setXmlCollapseContent}
									/>
								</FormCheckboxGroup>
							</FormSection>

							<FormSection title="Declaration">
								<FormCheckbox
									label="Include XML declaration"
									checked={xmlDeclaration}
									onCheckedChange={setXmlDeclaration}
								/>
								{xmlDeclaration ? (
									<div className="grid grid-cols-2 gap-2 pt-1">
										<FormInput
											label="Version"
											value={xmlDeclarationVersion}
											onValueChange={setXmlDeclarationVersion}
											placeholder="1.0"
											size="compact"
											className="font-mono"
										/>
										<FormInput
											label="Encoding"
											value={xmlDeclarationEncoding}
											onValueChange={setXmlDeclarationEncoding}
											placeholder="UTF-8"
											size="compact"
											className="font-mono"
										/>
									</div>
								) : null}
							</FormSection>

							<FormSection title="Tags">
								<FormCheckbox
									label="Use self-closing tags"
									checked={xmlSelfClosing}
									onCheckedChange={setXmlSelfClosing}
								/>
								<FormCheckbox
									label="Space before self-closing />"
									checked={xmlWhiteSpaceAtEndOfSelfclosingTag}
									onCheckedChange={setXmlWhiteSpaceAtEndOfSelfclosingTag}
								/>
							</FormSection>

							<FormSection title="Content">
								<FormCheckbox
									label="Wrap text in CDATA"
									checked={xmlCdata}
									onCheckedChange={setXmlCdata}
								/>
								{xmlCdata ? (
									<div className="pt-1">
										<FormInput
											label="CDATA Threshold (chars)"
											value={xmlCdataThresholdStr}
											onValueChange={setXmlCdataThresholdStr}
											placeholder="0"
											size="compact"
											className="font-mono"
											hint="0 = always use CDATA"
										/>
									</div>
								) : null}
								<FormCheckbox
									label="Escape special characters"
									checked={xmlEscapeText}
									onCheckedChange={setXmlEscapeText}
								/>
							</FormSection>

							<FormSection title="Sorting">
								<FormCheckboxGroup>
									<FormCheckbox
										label="Sort element keys"
										checked={xmlSortKeys}
										onCheckedChange={setXmlSortKeys}
									/>
									<FormCheckbox
										label="Sort attributes"
										checked={xmlSortAttributes}
										onCheckedChange={setXmlSortAttributes}
									/>
								</FormCheckboxGroup>
							</FormSection>

							<FormSection title="Comments">
								<FormInput
									label="Header Comment"
									value={xmlHeaderComment}
									onValueChange={setXmlHeaderComment}
									placeholder="Optional comment..."
									size="compact"
								/>
							</FormSection>
						</>
					) : null}
				</>
			)}
		/>
	);
}

export type { ConvertTabProps };
