// src/routes/hash-generator.tsx
import { createFileRoute } from '@tanstack/react-router';
import { useEffect, useMemo, useState } from 'react';
import { Hash, ShieldAlert, ShieldCheck } from 'lucide-react';

import { CopyButton } from '@/lib/components/action';
import { CodeEditor } from '@/lib/components/editor';
import { FormInfo, FormSection } from '@/lib/components/form';
import { SectionHeader } from '@/lib/components/layout';
import { ToolShell } from '@/lib/components/shell';
import { EmbeddedEmptyState, LiveStatusRegion, StatItem } from '@/lib/components/status';
import { Badge } from '@/lib/components/ui/badge';
import { Card, CardContent, CardHeader, CardTitle } from '@/lib/components/ui/card';
import {
	formatBytes,
	generateAllHashes,
	HASH_ALGORITHMS,
	SAMPLE_TEXT_FOR_HASH,
} from '@/lib/services/encoders';

export const Route = createFileRoute('/hash-generator')({
	component: HashGeneratorPage,
});

function HashGeneratorPage() {
	const [textInput, setTextInput] = useState('');
	const [showOptions, setShowOptions] = useState(true);

	useEffect(() => {
		document.title = 'Hash Generator — Kogu';
	}, []);

	const textHashes = useMemo(() => {
		if (!textInput.trim()) return [];
		return generateAllHashes(textInput);
	}, [textInput]);

	const textStats = useMemo(() => {
		const bytes = new TextEncoder().encode(textInput).length;
		return {
			chars: textInput.length,
			bytes,
			size: formatBytes(bytes),
		};
	}, [textInput]);

	const handlePaste = async () => {
		try {
			const text = await navigator.clipboard.readText();
			if (text) setTextInput(text);
		} catch {
			// Clipboard access denied
		}
	};

	const handleClear = () => setTextInput('');
	const handleSample = () => setTextInput(SAMPLE_TEXT_FOR_HASH);

	const isSecure = (algorithm: string): boolean =>
		HASH_ALGORITHMS.find((a) => a.algorithm === algorithm)?.secure ?? false;

	const hasInput = textInput.trim().length > 0;

	return (
		<ToolShell
			valid={hasInput ? true : null}
			showRail={showOptions}
			onShowRailChange={setShowOptions}
			statusContent={
				hasInput ? (
					<>
						<StatItem label="Chars" value={textStats.chars} />
						<StatItem label="Size" value={textStats.size} />
					</>
				) : null
			}
			rail={
				<>
					<FormSection title="About Hash">
						<FormInfo>
							<ul className="list-inside list-disc space-y-0.5">
								<li>One-way cryptographic function</li>
								<li>Same input always produces same output</li>
								<li>Cannot be reversed to original data</li>
								<li>Small change in input = completely different hash</li>
							</ul>
						</FormInfo>
					</FormSection>
					<FormSection title="Security">
						<FormInfo showIcon={false}>
							<div className="space-y-1">
								<div className="flex items-center gap-2">
									<ShieldCheck className="h-3 w-3 text-success" />
									<span className="text-success">Secure:</span>
									<span>SHA-256, SHA-384, SHA-512</span>
								</div>
								<div className="flex items-center gap-2">
									<ShieldAlert className="h-3 w-3 text-warning" />
									<span className="text-warning">Weak:</span>
									<span>MD5, SHA-1</span>
								</div>
							</div>
						</FormInfo>
					</FormSection>
				</>
			}
		>
			<div className="flex h-full flex-col overflow-hidden">
				<div className="h-1/3 shrink-0 border-b">
					<CodeEditor
						title="Input Text"
						value={textInput}
						onChange={setTextInput}
						mode="input"
						editorMode="plain"
						placeholder="Enter text to hash..."
						showViewToggle={false}
						onPaste={handlePaste}
						onClear={handleClear}
						onSample={handleSample}
					/>
				</div>
				<div className="flex flex-1 flex-col overflow-hidden">
					<SectionHeader title="Hash Results" />
					<LiveStatusRegion className="flex-1 overflow-auto p-4">
						{textHashes.length > 0 ? (
							<div className="space-y-3">
								{textHashes.map((result) => (
									<Card key={result.algorithm} density="compact">
										<CardHeader className="flex flex-row items-center justify-between space-y-0 pb-3">
											<div className="flex items-center gap-2">
												<CardTitle className="font-mono text-sm">{result.algorithm}</CardTitle>
												<span className="text-xs tabular-nums text-muted-foreground">
													({result.bits} bits)
												</span>
												{isSecure(result.algorithm) ? (
													<Badge variant="outline" className="gap-1 bg-success/10 text-success">
														<ShieldCheck className="h-3 w-3" />
														Secure
													</Badge>
												) : (
													<Badge variant="outline" className="gap-1 bg-warning/10 text-warning">
														<ShieldAlert className="h-3 w-3" />
														Weak
													</Badge>
												)}
											</div>
											<CopyButton
												text={result.hash}
												toastLabel={result.algorithm}
												size="sm"
												showLabel
												className="h-7"
											/>
										</CardHeader>
										<CardContent>
											<code className="block break-all rounded bg-muted p-2 font-mono text-xs">
												{result.hash}
											</code>
										</CardContent>
									</Card>
								))}
							</div>
						) : (
							<EmbeddedEmptyState
								icon={Hash}
								title="Enter text to hash"
								description="Type or paste content above to compute MD5, SHA-1, SHA-256, and more."
								fillHeight
							/>
						)}
					</LiveStatusRegion>
				</div>
			</div>
		</ToolShell>
	);
}

// src/routes/hash-generator/+page.svelte
<script lang="ts">
	import { Hash, ShieldAlert, ShieldCheck } from '@lucide/svelte';
	import { CopyButton } from '$lib/components/action';
	import { CodeEditor } from '$lib/components/editor';
	import { FormInfo, FormSection } from '$lib/components/form';
	import { SectionHeader } from '$lib/components/layout';
	import { ToolShell } from '$lib/components/shell';
	import { EmptyState, StatItem } from '$lib/components/status';
	import {
		formatBytes,
		generateAllHashes,
		HASH_ALGORITHMS,
		type HashResult,
		SAMPLE_TEXT_FOR_HASH,
	} from '$lib/services/encoders.js';

	// State
	let textInput = $state('');
	let showOptions = $state(true);

	// Computed text hashes
	const textHashes = $derived.by((): HashResult[] => {
		if (!textInput.trim()) return [];
		return generateAllHashes(textInput);
	});

	// Stats
	const textStats = $derived.by(() => {
		const text = textInput || '';
		const bytes = new TextEncoder().encode(text).length;
		return {
			chars: text.length,
			bytes,
			size: formatBytes(bytes),
		};
	});

	// Handlers
	const handlePaste = async () => {
		try {
			const text = await navigator.clipboard.readText();
			if (text) textInput = text;
		} catch {
			// Clipboard access denied
		}
	};

	const handleClear = () => {
		textInput = '';
	};

	const handleSample = () => {
		textInput = SAMPLE_TEXT_FOR_HASH;
	};

	// Get security badge for algorithm
	const getSecurityBadge = (algorithm: string) => {
		const algo = HASH_ALGORITHMS.find((a) => a.algorithm === algorithm);
		return algo?.secure ?? false;
	};
</script>

<svelte:head>
	<title>Hash Generator - Kogu</title>
</svelte:head>

<ToolShell valid={textInput.trim() ? true : null} bind:showRail={showOptions}>
	{#snippet statusContent()}
		{#if textInput.trim()}
			<StatItem label="Chars" value={textStats.chars} />
			<StatItem label="Size" value={textStats.size} />
		{/if}
	{/snippet}

	{#snippet rail()}
		<FormSection title="About Hash">
			<FormInfo>
				<ul class="list-inside list-disc space-y-0.5">
					<li>One-way cryptographic function</li>
					<li>Same input always produces same output</li>
					<li>Cannot be reversed to original data</li>
					<li>Small change in input = completely different hash</li>
				</ul>
			</FormInfo>
		</FormSection>

		<FormSection title="Security">
			<FormInfo showIcon={false}>
				<div class="space-y-1">
					<div class="flex items-center gap-2">
						<ShieldCheck class="h-3 w-3 text-success" />
						<span class="text-success">Secure:</span>
						<span>SHA-256, SHA-384, SHA-512</span>
					</div>
					<div class="flex items-center gap-2">
						<ShieldAlert class="h-3 w-3 text-warning" />
						<span class="text-warning">Weak:</span>
						<span>MD5, SHA-1</span>
					</div>
				</div>
			</FormInfo>
		</FormSection>
	{/snippet}

	<!-- Main Content: Input + Results -->
	<div class="flex h-full flex-col overflow-hidden">
		<!-- Input Editor -->
		<div class="h-1/3 shrink-0 border-b">
			<CodeEditor
				title="Input Text"
				bind:value={textInput}
				mode="input"
				editorMode="plain"
				placeholder="Enter text to hash..."
				showViewToggle={false}
				onpaste={handlePaste}
				onclear={handleClear}
				onsample={handleSample}
			/>
		</div>

		<!-- Hash Results -->
		<div class="flex flex-1 flex-col overflow-hidden">
			<SectionHeader title="Hash Results" />
			<div class="flex-1 overflow-auto p-4">
				{#if textHashes.length > 0}
					<div class="space-y-3">
						{#each textHashes as result}
							<div class="rounded-lg border bg-muted/30 p-3">
								<div class="mb-2 flex items-center justify-between">
									<div class="flex items-center gap-2">
										<span class="font-mono text-sm font-medium">{result.algorithm}</span>
										<span class="text-xs text-muted-foreground">({result.bits} bits)</span>
										{#if getSecurityBadge(result.algorithm)}
											<span class="flex items-center gap-1 text-xs text-success">
												<ShieldCheck class="h-3 w-3" />
												Secure
											</span>
										{:else}
											<span class="flex items-center gap-1 text-xs text-warning">
												<ShieldAlert class="h-3 w-3" />
												Weak
											</span>
										{/if}
									</div>
									<CopyButton
										text={result.hash}
										toastLabel={result.algorithm}
										size="sm"
										showLabel
										class="h-6"
									/>
								</div>
								<code class="block break-all rounded bg-muted p-2 font-mono text-xs"
									>{result.hash}</code
								>
							</div>
						{/each}
					</div>
				{:else}
					<EmptyState icon={Hash} title="Enter text to generate hashes" />
				{/if}
			</div>
		</div>
	</div>
</ToolShell>
