// src/routes/xml-formatter/+page.svelte
<script lang="ts">
	import { ArrowRightLeft, Code2, FileCheck, GitCompare, Play, Search } from '@lucide/svelte';
	import { FormatterPage } from '$lib/components/tool/index.js';
	import { calculateXmlStats, type XmlStats } from '$lib/services/formatters.js';
	import {
		CompareTab,
		ConvertTab,
		FormatTab,
		GenerateTab,
		QueryTab,
		SchemaTab,
	} from './tabs/index.js';

	type TabType = 'format' | 'query' | 'compare' | 'convert' | 'schema' | 'generate';

	const tabs = [
		{ value: 'format' as const, label: 'Format', icon: Play },
		{ value: 'query' as const, label: 'Query', icon: Search },
		{ value: 'compare' as const, label: 'Compare', icon: GitCompare },
		{ value: 'convert' as const, label: 'Convert', icon: ArrowRightLeft },
		{ value: 'schema' as const, label: 'Schema', icon: FileCheck },
		{ value: 'generate' as const, label: 'Generate', icon: Code2 },
	] as const;
</script>

<svelte:head>
	<title>XML Formatter - Kogu</title>
</svelte:head>

<FormatterPage
	title="XML Formatter"
	{tabs}
	defaultTab="format"
	defaultInput=""
	calculateStats={(input: string) => calculateXmlStats(input) as XmlStats | null}
>
	{#snippet statsSnippet(stats: XmlStats)}
		<span class="text-muted-foreground"
			>Elements: <strong class="text-foreground">{stats.elements}</strong></span
		>
		<span class="text-muted-foreground"
			>Attributes: <strong class="text-foreground">{stats.attributes}</strong></span
		>
		<span class="text-muted-foreground"
			>Depth: <strong class="text-foreground">{stats.depth}</strong></span
		>
		<span class="text-muted-foreground"
			>Size: <strong class="text-foreground">{stats.size}</strong></span
		>
	{/snippet}

	{#snippet tabContents(tab: TabType, sharedInput: string, setSharedInput: (value: string) => void, onStatsChange: (stats: { input: string; valid: boolean | null; error: string }) => void)}
		{#if tab === 'format'}
			<FormatTab input={sharedInput} onInputChange={setSharedInput} {onStatsChange} />
		{:else if tab === 'query'}
			<QueryTab input={sharedInput} onInputChange={setSharedInput} {onStatsChange} />
		{:else if tab === 'compare'}
			<CompareTab input={sharedInput} onInputChange={setSharedInput} {onStatsChange} />
		{:else if tab === 'convert'}
			<ConvertTab input={sharedInput} onInputChange={setSharedInput} {onStatsChange} />
		{:else if tab === 'schema'}
			<SchemaTab input={sharedInput} onInputChange={setSharedInput} {onStatsChange} />
		{:else if tab === 'generate'}
			<GenerateTab input={sharedInput} onInputChange={setSharedInput} {onStatsChange} />
		{/if}
	{/snippet}
</FormatterPage>

// src/routes/xml-formatter.tsx
import { createFileRoute } from '@tanstack/react-router';

import {
	CompareTab,
	ConvertTab,
	FormatTab,
	GenerateTab,
	QueryTab,
	SchemaTab,
} from '@/lib/components/formatter-tabs/xml';
import { TabbedFormatterPage } from '@/lib/components/template';
import { StatItem } from '@/lib/components/status';
import { calculateXmlStats, type XmlStats } from '@/lib/services/formatters';

export const Route = createFileRoute('/xml-formatter')({
	component: XmlFormatterPage,
});

function XmlFormatterPage() {
	return (
		<TabbedFormatterPage<XmlStats>
			title="XML Formatter"
			calculateStats={calculateXmlStats}
			persistKey="xml-formatter"
			renderStatusContent={(liveStats) =>
				liveStats ? (
					<>
						<StatItem label="Elements" value={liveStats.elements} />
						<StatItem label="Attributes" value={liveStats.attributes} />
						<StatItem label="Depth" value={liveStats.depth} />
						<StatItem label="Size" value={liveStats.size} />
					</>
				) : (
					<span className="text-xs text-muted-foreground/70">
						Paste, drop, or load sample to get started
					</span>
				)
			}
			renderTabContent={({ tab, input, onInputChange, onStatsChange }) => {
				switch (tab) {
					case 'format':
						return (
							<FormatTab
								input={input}
								onInputChange={onInputChange}
								onStatsChange={onStatsChange}
							/>
						);
					case 'query':
						return (
							<QueryTab input={input} onInputChange={onInputChange} onStatsChange={onStatsChange} />
						);
					case 'compare':
						return (
							<CompareTab
								input={input}
								onInputChange={onInputChange}
								onStatsChange={onStatsChange}
							/>
						);
					case 'convert':
						return (
							<ConvertTab
								input={input}
								onInputChange={onInputChange}
								onStatsChange={onStatsChange}
							/>
						);
					case 'schema':
						return (
							<SchemaTab
								input={input}
								onInputChange={onInputChange}
								onStatsChange={onStatsChange}
							/>
						);
					case 'generate':
						return (
							<GenerateTab
								input={input}
								onInputChange={onInputChange}
								onStatsChange={onStatsChange}
							/>
						);
					default:
						return null;
				}
			}}
		/>
	);
}
