// src/routes/yaml-formatter/+page.svelte
<script lang="ts">
	import { TabbedFormatterPage } from '$lib/components/template';
	import { StatItem } from '$lib/components/status';
	import { calculateYamlStats, type YamlStats } from '$lib/services/formatters';
	import type { TabStats } from '$lib/hooks';
	import {
		CompareTab,
		ConvertTab,
		FormatTab,
		GenerateTab,
		QueryTab,
		SchemaTab,
	} from './tabs/index.js';
</script>

<TabbedFormatterPage
	title="YAML Formatter"
	calculateStats={calculateYamlStats}
	persistKey="yaml-formatter"
>
	{#snippet renderStatusContent(stats: unknown)}
		{@const liveStats = stats as YamlStats | null}
		{#if liveStats}
			<StatItem label="Keys" value={liveStats.keys} />
			<StatItem label="Values" value={liveStats.values} />
			<StatItem label="Depth" value={liveStats.depth} />
			<StatItem label="Size" value={liveStats.size} />
		{/if}
	{/snippet}

	{#snippet renderTabContent({
		tab,
		input,
		onInputChange,
		onStatsChange,
	}: {
		tab: string;
		input: string;
		onInputChange: (v: string) => void;
		onStatsChange: (s: TabStats) => void;
	})}
		{#if tab === 'format'}
			<FormatTab {input} {onInputChange} {onStatsChange} />
		{:else if tab === 'query'}
			<QueryTab {input} {onInputChange} {onStatsChange} />
		{:else if tab === 'compare'}
			<CompareTab {input} {onInputChange} {onStatsChange} />
		{:else if tab === 'convert'}
			<ConvertTab {input} {onInputChange} {onStatsChange} />
		{:else if tab === 'schema'}
			<SchemaTab {input} {onInputChange} {onStatsChange} />
		{:else if tab === 'generate'}
			<GenerateTab {input} {onInputChange} {onStatsChange} />
		{/if}
	{/snippet}
</TabbedFormatterPage>

// src/routes/yaml-formatter.tsx
import { createFileRoute } from '@tanstack/react-router';

import {
	CompareTab,
	ConvertTab,
	FormatTab,
	GenerateTab,
	QueryTab,
	SchemaTab,
} from '@/lib/components/formatter-tabs/yaml';
import { StatItem } from '@/lib/components/status';
import { TabbedFormatterPage } from '@/lib/components/template';
import { calculateYamlStats, type YamlStats } from '@/lib/services/formatters';

export const Route = createFileRoute('/yaml-formatter')({
	component: YamlFormatterPage,
});

function YamlFormatterPage() {
	return (
		<TabbedFormatterPage<YamlStats>
			title="YAML Formatter"
			calculateStats={calculateYamlStats}
			persistKey="yaml-formatter"
			renderStatusContent={(liveStats) =>
				liveStats ? (
					<>
						<StatItem label="Keys" value={liveStats.keys} />
						<StatItem label="Values" value={liveStats.values} />
						<StatItem label="Depth" value={liveStats.depth} />
						<StatItem label="Size" value={liveStats.size} />
					</>
				) : null
			}
			renderTabContent={({ tab, input, onInputChange, onStatsChange }) => {
				switch (tab) {
					case 'format':
						return (
							<FormatTab
								input={input}
								onInputChange={onInputChange}
								onStatsChange={onStatsChange}
							/>
						);
					case 'query':
						return (
							<QueryTab input={input} onInputChange={onInputChange} onStatsChange={onStatsChange} />
						);
					case 'compare':
						return (
							<CompareTab
								input={input}
								onInputChange={onInputChange}
								onStatsChange={onStatsChange}
							/>
						);
					case 'convert':
						return (
							<ConvertTab
								input={input}
								onInputChange={onInputChange}
								onStatsChange={onStatsChange}
							/>
						);
					case 'schema':
						return (
							<SchemaTab
								input={input}
								onInputChange={onInputChange}
								onStatsChange={onStatsChange}
							/>
						);
					case 'generate':
						return (
							<GenerateTab
								input={input}
								onInputChange={onInputChange}
								onStatsChange={onStatsChange}
							/>
						);
					default:
						return null;
				}
			}}
		/>
	);
}
