// src/routes/sql-formatter.tsx
import { createFileRoute } from '@tanstack/react-router';
import { useEffect, useState } from 'react';
import { Database } from 'lucide-react';
import { toast } from 'sonner';
import type { SqlLanguage } from 'sql-formatter';

import { CodeEditor } from '@/lib/components/editor';
import {
	FormCheckbox,
	FormCheckboxGroup,
	FormMode,
	FormSection,
	FormSelect,
} from '@/lib/components/form';
import { SectionHeader, SplitPane } from '@/lib/components/layout';
import { ToolShell } from '@/lib/components/shell';
import { EmbeddedEmptyState, StatItem } from '@/lib/components/status';
import {
	calculateSqlStats,
	defaultSqlFormatOptions,
	formatSql,
	minifySql,
	SAMPLE_SQL,
	SQL_INDENT_STYLE_OPTIONS,
	SQL_KEYWORD_CASE_OPTIONS,
	SQL_LANGUAGE_OPTIONS,
	SQL_LOGICAL_OPERATOR_OPTIONS,
	type SqlFormatOptions,
} from '@/lib/services/formatters';

type Mode = 'format' | 'minify';
type KeywordCase = 'upper' | 'lower' | 'preserve';
type IndentStyle = 'standard' | 'tabularLeft' | 'tabularRight';
type LogicalOperatorNewline = 'before' | 'after';

export const Route = createFileRoute('/sql-formatter')({
	component: SqlFormatterPage,
});

function SqlFormatterPage() {
	const [mode, setMode] = useState<Mode>('format');
	const [input, setInput] = useState('');
	const [showOptions, setShowOptions] = useState(true);

	const [language, setLanguage] = useState<SqlLanguage>(defaultSqlFormatOptions.language);
	const [tabWidthStr, setTabWidthStr] = useState(String(defaultSqlFormatOptions.tabWidth));
	const [useTabs, setUseTabs] = useState<boolean>(defaultSqlFormatOptions.useTabs);
	const [keywordCase, setKeywordCase] = useState<KeywordCase>(defaultSqlFormatOptions.keywordCase);
	const [indentStyle, setIndentStyle] = useState<IndentStyle>(defaultSqlFormatOptions.indentStyle);
	const [logicalOperatorNewline, setLogicalOperatorNewline] = useState<LogicalOperatorNewline>(
		defaultSqlFormatOptions.logicalOperatorNewline
	);
	const [expressionWidthStr, setExpressionWidthStr] = useState(
		String(defaultSqlFormatOptions.expressionWidth)
	);
	const [linesBetweenQueriesStr, setLinesBetweenQueriesStr] = useState(
		String(defaultSqlFormatOptions.linesBetweenQueries)
	);
	const [denseOperators, setDenseOperators] = useState<boolean>(
		defaultSqlFormatOptions.denseOperators
	);
	const [newlineBeforeSemicolon, setNewlineBeforeSemicolon] = useState<boolean>(
		defaultSqlFormatOptions.newlineBeforeSemicolon
	);

	useEffect(() => {
		document.title = 'SQL Formatter — Kogu';
	}, []);

	const tabWidth = Number.parseInt(tabWidthStr, 10) || 2;
	const expressionWidth = Number.parseInt(expressionWidthStr, 10) || 50;
	const linesBetweenQueries = Number.parseInt(linesBetweenQueriesStr, 10) || 1;

	const formatOptions: Partial<SqlFormatOptions> = {
		language,
		tabWidth,
		useTabs,
		keywordCase,
		indentStyle,
		logicalOperatorNewline,
		expressionWidth,
		linesBetweenQueries,
		denseOperators,
		newlineBeforeSemicolon,
	};

	const stats = (() => {
		if (!input.trim()) return null;
		try {
			return calculateSqlStats(input);
		} catch {
			return null;
		}
	})();

	const { output, error } = ((): { output: string; error: string } => {
		if (!input.trim()) return { output: '', error: '' };
		try {
			const result = mode === 'minify' ? minifySql(input) : formatSql(input, formatOptions);
			return { output: result, error: '' };
		} catch (e) {
			return { output: '', error: e instanceof Error ? e.message : 'Invalid SQL' };
		}
	})();

	const valid: boolean | null = !input.trim() ? null : !error;
	const selectedLanguageLabel =
		SQL_LANGUAGE_OPTIONS.find((opt) => opt.value === language)?.label ?? 'Standard SQL';

	const handlePaste = async () => {
		try {
			const text = await navigator.clipboard.readText();
			if (text) setInput(text);
		} catch {
			// Clipboard access denied
		}
	};

	const handleClear = () => setInput('');

	const handleCopy = async () => {
		try {
			await navigator.clipboard.writeText(output);
			toast.success('Copied to clipboard');
		} catch {
			toast.error('Failed to copy to clipboard');
		}
	};

	const handleSample = () => setInput(SAMPLE_SQL);

	return (
		<ToolShell
			valid={valid}
			error={error || undefined}
			showRail={showOptions}
			onShowRailChange={setShowOptions}
			statusContent={
				stats ? (
					<>
						<StatItem label="Statements" value={stats.statements} />
						<StatItem label="Size" value={stats.size} />
					</>
				) : null
			}
			rail={
				<>
					<FormSection title="Mode">
						<FormMode
							value={mode}
							onValueChange={setMode}
							options={[
								{ value: 'format', label: 'Format' },
								{ value: 'minify', label: 'Minify' },
							]}
						/>
						<div className="mt-2 rounded-md bg-muted/50 p-2 text-xs text-muted-foreground">
							<span className="font-medium text-foreground">Dialect:</span> {selectedLanguageLabel}
						</div>
					</FormSection>

					<FormSection title="SQL Dialect">
						<FormSelect
							label="Language"
							value={language}
							onValueChange={(v) => setLanguage(v as SqlLanguage)}
							options={SQL_LANGUAGE_OPTIONS.map((opt) => ({
								value: opt.value,
								label: opt.label,
							}))}
						/>
					</FormSection>

					<FormSection title="Indentation">
						<div className="grid grid-cols-2 gap-2">
							<FormSelect
								label="Width"
								value={tabWidthStr}
								onValueChange={setTabWidthStr}
								options={['1', '2', '3', '4', '8']}
							/>
							<FormSelect
								label="Style"
								value={indentStyle}
								onValueChange={(v) => setIndentStyle(v as IndentStyle)}
								options={SQL_INDENT_STYLE_OPTIONS.map((opt) => ({
									value: opt.value,
									label: opt.label,
									description: opt.description,
								}))}
							/>
						</div>
						<FormCheckbox
							label="Use tabs instead of spaces"
							checked={useTabs}
							onCheckedChange={setUseTabs}
						/>
					</FormSection>

					<FormSection title="Keywords">
						<FormSelect
							label="Keyword Case"
							value={keywordCase}
							onValueChange={(v) => setKeywordCase(v as KeywordCase)}
							options={SQL_KEYWORD_CASE_OPTIONS.map((opt) => ({
								value: opt.value,
								label: opt.label,
							}))}
						/>
					</FormSection>

					<FormSection title="Layout">
						<FormSelect
							label="Logical Operators"
							value={logicalOperatorNewline}
							onValueChange={(v) => setLogicalOperatorNewline(v as LogicalOperatorNewline)}
							options={SQL_LOGICAL_OPERATOR_OPTIONS.map((opt) => ({
								value: opt.value,
								label: opt.label,
								description: opt.description,
							}))}
						/>
						<FormSelect
							label="Expression Width"
							value={expressionWidthStr}
							onValueChange={setExpressionWidthStr}
							options={['20', '30', '40', '50', '60', '80', '100', '120']}
						/>
						<FormSelect
							label="Lines Between Queries"
							value={linesBetweenQueriesStr}
							onValueChange={setLinesBetweenQueriesStr}
							options={['0', '1', '2', '3', '4', '5']}
						/>
					</FormSection>

					<FormSection title="Spacing">
						<FormCheckboxGroup>
							<FormCheckbox
								label="Dense operators (no spaces)"
								checked={denseOperators}
								onCheckedChange={setDenseOperators}
							/>
							<FormCheckbox
								label="Newline before semicolon"
								checked={newlineBeforeSemicolon}
								onCheckedChange={setNewlineBeforeSemicolon}
							/>
						</FormCheckboxGroup>
					</FormSection>
				</>
			}
		>
			<SplitPane
				className="h-full flex-1"
				left={
					<CodeEditor
						title="Input"
						value={input}
						onChange={setInput}
						mode="input"
						editorMode="sql"
						placeholder="Enter SQL here..."
						onSample={handleSample}
						onPaste={handlePaste}
						onClear={handleClear}
					/>
				}
				right={
					!input.trim() ? (
						<div className="flex h-full flex-col overflow-hidden">
							<SectionHeader title="Output" />
							<div className="flex-1">
								<EmbeddedEmptyState
									icon={Database}
									title="Enter SQL to format"
									description="The formatted (or minified) statement will appear here."
									fillHeight
								/>
							</div>
						</div>
					) : (
						<CodeEditor
							title="Output"
							value={output}
							mode="readonly"
							editorMode="sql"
							placeholder="Formatted output..."
							onCopy={handleCopy}
						/>
					)
				}
			/>
		</ToolShell>
	);
}

// src/routes/sql-formatter/+page.svelte
<script lang="ts">
	import type { SqlLanguage } from 'sql-formatter';
	import { CodeEditor } from '$lib/components/editor';
	import {
		FormCheckbox,
		FormCheckboxGroup,
		FormMode,
		FormSection,
		FormSelect,
	} from '$lib/components/form';
	import { SplitPane } from '$lib/components/layout';
	import { ToolShell } from '$lib/components/shell';
	import { StatItem } from '$lib/components/status';
	import {
		calculateSqlStats,
		defaultSqlFormatOptions,
		formatSql,
		minifySql,
		SAMPLE_SQL,
		SQL_INDENT_STYLE_OPTIONS,
		SQL_KEYWORD_CASE_OPTIONS,
		SQL_LANGUAGE_OPTIONS,
		SQL_LOGICAL_OPERATOR_OPTIONS,
		type SqlFormatOptions,
		type SqlStats,
	} from '$lib/services/formatters';

	type Mode = 'format' | 'minify';

	// State
	let mode = $state<Mode>('format');
	let input = $state('');
	let showOptions = $state(true);

	// Format options
	let language = $state<SqlLanguage>(defaultSqlFormatOptions.language);
	let tabWidthStr = $state(String(defaultSqlFormatOptions.tabWidth));
	let useTabs = $state(defaultSqlFormatOptions.useTabs);
	let keywordCase = $state<'upper' | 'lower' | 'preserve'>(defaultSqlFormatOptions.keywordCase);
	let indentStyle = $state<'standard' | 'tabularLeft' | 'tabularRight'>(
		defaultSqlFormatOptions.indentStyle
	);
	let logicalOperatorNewline = $state<'before' | 'after'>(
		defaultSqlFormatOptions.logicalOperatorNewline
	);
	let expressionWidthStr = $state(String(defaultSqlFormatOptions.expressionWidth));
	let linesBetweenQueriesStr = $state(String(defaultSqlFormatOptions.linesBetweenQueries));
	let denseOperators = $state(defaultSqlFormatOptions.denseOperators);
	let newlineBeforeSemicolon = $state(defaultSqlFormatOptions.newlineBeforeSemicolon);

	// Derived numeric values
	const tabWidth = $derived(Number.parseInt(tabWidthStr, 10) || 2);
	const expressionWidth = $derived(Number.parseInt(expressionWidthStr, 10) || 50);
	const linesBetweenQueries = $derived(Number.parseInt(linesBetweenQueriesStr, 10) || 1);

	// Format options object
	const formatOptions = $derived<Partial<SqlFormatOptions>>({
		language,
		tabWidth,
		useTabs,
		keywordCase,
		indentStyle,
		logicalOperatorNewline,
		expressionWidth,
		linesBetweenQueries,
		denseOperators,
		newlineBeforeSemicolon,
	});

	// Stats calculation
	const stats = $derived.by((): SqlStats | null => {
		if (!input.trim()) return null;
		try {
			return calculateSqlStats(input);
		} catch {
			return null;
		}
	});

	// Output calculation
	const formatResult = $derived.by((): { output: string; error: string } => {
		if (!input.trim()) return { output: '', error: '' };
		try {
			const output = mode === 'minify' ? minifySql(input) : formatSql(input, formatOptions);
			return { output, error: '' };
		} catch (e) {
			return { output: '', error: e instanceof Error ? e.message : 'Invalid SQL' };
		}
	});

	const output = $derived(formatResult.output);
	const error = $derived(formatResult.error);

	// Validation state
	const valid = $derived.by((): boolean | null => {
		if (!input.trim()) return null;
		return !error;
	});

	// Language display
	const selectedLanguageLabel = $derived(
		SQL_LANGUAGE_OPTIONS.find((opt) => opt.value === language)?.label ?? 'Standard SQL'
	);

	// Handlers
	const handlePaste = async () => {
		try {
			const text = await navigator.clipboard.readText();
			if (text) input = text;
		} catch {
			// Clipboard access denied
		}
	};

	const handleClear = () => {
		input = '';
	};

	const handleCopy = async () => {
		try {
			await navigator.clipboard.writeText(output);
		} catch {
			// Clipboard access denied
		}
	};

	const handleSample = () => {
		input = SAMPLE_SQL;
	};
</script>

<svelte:head>
	<title>SQL Formatter - Kogu</title>
</svelte:head>

<ToolShell {valid} {error} bind:showRail={showOptions}>
	{#snippet statusContent()}
		{#if stats}
			<StatItem label="Statements" value={stats.statements} />
			<StatItem label="Size" value={stats.size} />
		{/if}
	{/snippet}

	{#snippet rail()}
		<FormSection title="Mode">
			<FormMode
				value={mode}
				onchange={(v) => (mode = v as Mode)}
				options={[
					{ value: 'format', label: 'Format' },
					{ value: 'minify', label: 'Minify' },
				]}
			/>
			<div class="mt-2 rounded-md bg-muted/50 p-2 text-xs text-muted-foreground">
				<span class="font-medium text-foreground">Dialect:</span>
				{selectedLanguageLabel}
			</div>
		</FormSection>

		<FormSection title="SQL Dialect">
			<FormSelect
				label="Language"
				value={language}
				onchange={(v) => (language = v as SqlLanguage)}
				options={SQL_LANGUAGE_OPTIONS.map((opt) => ({ value: opt.value, label: opt.label }))}
			/>
		</FormSection>

		<FormSection title="Indentation">
			<div class="grid grid-cols-2 gap-2">
				<FormSelect
					label="Width"
					value={tabWidthStr}
					onchange={(v) => (tabWidthStr = v)}
					options={['1', '2', '3', '4', '8']}
				/>
				<FormSelect
					label="Style"
					value={indentStyle}
					onchange={(v) => (indentStyle = v as 'standard' | 'tabularLeft' | 'tabularRight')}
					options={SQL_INDENT_STYLE_OPTIONS.map((opt) => ({
						value: opt.value,
						label: opt.label,
						description: opt.description,
					}))}
				/>
			</div>
			<FormCheckbox label="Use tabs instead of spaces" bind:checked={useTabs} />
		</FormSection>

		<FormSection title="Keywords">
			<FormSelect
				label="Keyword Case"
				value={keywordCase}
				onchange={(v) => (keywordCase = v as 'upper' | 'lower' | 'preserve')}
				options={SQL_KEYWORD_CASE_OPTIONS.map((opt) => ({
					value: opt.value,
					label: opt.label,
				}))}
			/>
		</FormSection>

		<FormSection title="Layout">
			<FormSelect
				label="Logical Operators"
				value={logicalOperatorNewline}
				onchange={(v) => (logicalOperatorNewline = v as 'before' | 'after')}
				options={SQL_LOGICAL_OPERATOR_OPTIONS.map((opt) => ({
					value: opt.value,
					label: opt.label,
					description: opt.description,
				}))}
			/>
			<FormSelect
				label="Expression Width"
				value={expressionWidthStr}
				onchange={(v) => (expressionWidthStr = v)}
				options={['20', '30', '40', '50', '60', '80', '100', '120']}
			/>
			<FormSelect
				label="Lines Between Queries"
				value={linesBetweenQueriesStr}
				onchange={(v) => (linesBetweenQueriesStr = v)}
				options={['0', '1', '2', '3', '4', '5']}
			/>
		</FormSection>

		<FormSection title="Spacing">
			<FormCheckboxGroup>
				<FormCheckbox label="Dense operators (no spaces)" bind:checked={denseOperators} />
				<FormCheckbox label="Newline before semicolon" bind:checked={newlineBeforeSemicolon} />
			</FormCheckboxGroup>
		</FormSection>
	{/snippet}

	<SplitPane class="h-full flex-1">
		{#snippet left()}
			<CodeEditor
				title="Input"
				value={input}
				onchange={(v) => (input = v)}
				mode="input"
				editorMode="sql"
				placeholder="Enter SQL here..."
				onsample={handleSample}
				onpaste={handlePaste}
				onclear={handleClear}
			/>
		{/snippet}
		{#snippet right()}
			<CodeEditor
				title="Output"
				value={output}
				mode="readonly"
				editorMode="sql"
				placeholder="Formatted output..."
				oncopy={handleCopy}
			/>
		{/snippet}
	</SplitPane>
</ToolShell>
