// src/routes/settings.tsx
import { createFileRoute } from '@tanstack/react-router';
import { useEffect, useRef, useState } from 'react';
import { toast } from 'sonner';
import { confirm } from '@tauri-apps/plugin-dialog';
import { AlertTriangle, Check, ChevronsUpDown, Globe, RotateCcw, Settings } from 'lucide-react';

import { Alert, AlertDescription, AlertTitle } from '@/lib/components/ui/alert';
import { Button } from '@/lib/components/ui/button';
import {
	Card,
	CardContent,
	CardDescription,
	CardHeader,
	CardTitle,
} from '@/lib/components/ui/card';
import {
	Command,
	CommandEmpty,
	CommandGroup,
	CommandInput,
	CommandItem,
	CommandList,
} from '@/lib/components/ui/command';
import { Label } from '@/lib/components/ui/label';
import { Popover, PopoverContent, PopoverTrigger } from '@/lib/components/ui/popover';
import { FormCheckbox, FormSlider } from '@/lib/components/form';
import {
	applyAllSettings,
	DEFAULT_SETTINGS,
	type FontSettings,
	getMonospaceSystemFonts,
	getSettings,
	getSettingsFilePath,
	getSystemFonts,
	resetSettings,
	updateSettings,
} from '@/lib/services/settings';
import { getGoogleFontsByCategory, loadGoogleFont } from '@/lib/services/google-fonts';

export const Route = createFileRoute('/settings')({
	component: SettingsPage,
});

function SettingsPage() {
	const [fontSettings, setFontSettings] = useState<FontSettings>({ ...DEFAULT_SETTINGS.font });
	const [systemFonts, setSystemFonts] = useState<readonly string[]>([]);
	const [monospaceFonts, setMonospaceFonts] = useState<readonly string[]>([]);
	const [settingsFilePath, setSettingsFilePath] = useState('');
	const [uiFontOpen, setUiFontOpen] = useState(false);
	const [codeFontOpen, setCodeFontOpen] = useState(false);

	const saveTimerRef = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);
	const initializedRef = useRef(false);

	const googleUiFonts = getGoogleFontsByCategory('sans-serif');
	const googleCodeFonts = getGoogleFontsByCategory('monospace');

	useEffect(() => {
		document.title = 'Settings — Kogu';
	}, []);

	useEffect(() => {
		getSettings()
			.then((settings) => {
				setFontSettings({ ...settings.font });
				initializedRef.current = true;
			})
			.catch(() => {
				initializedRef.current = true;
			});

		getSystemFonts()
			.then(setSystemFonts)
			.catch(() => {});
		getMonospaceSystemFonts()
			.then(setMonospaceFonts)
			.catch(() => {});
		getSettingsFilePath()
			.then(setSettingsFilePath)
			.catch(() => {});
	}, []);

	useEffect(() => {
		if (!initializedRef.current) return;
		const settings = { font: fontSettings };
		clearTimeout(saveTimerRef.current);
		saveTimerRef.current = setTimeout(() => {
			updateSettings(settings)
				.then(() => applyAllSettings(settings))
				.catch(() => toast.error('Failed to save settings'));
		}, 300);
		return () => clearTimeout(saveTimerRef.current);
	}, [fontSettings]);

	const handleReset = async () => {
		const confirmed = await confirm(
			'This will reset all settings including fonts and window position.',
			{
				title: 'Reset All Settings',
				kind: 'warning',
				okLabel: 'Reset',
				cancelLabel: 'Cancel',
			}
		);
		if (!confirmed) return;

		const defaults = await resetSettings();
		setFontSettings({ ...defaults.font });
		applyAllSettings(defaults);
		toast.success('All settings have been reset');
	};

	const selectGoogleFont = (
		field: 'ui_family' | 'code_family',
		fontName: string,
		closePopover: () => void
	) => {
		loadGoogleFont(fontName);
		setFontSettings((prev) => ({ ...prev, [field]: fontName }));
		closePopover();
	};

	return (
		<div className="flex h-full flex-col">
			<main className="flex-1 overflow-y-auto p-6">
				<div className="mx-auto max-w-2xl space-y-6">
					<div className="flex items-center gap-3">
						<Settings className="h-6 w-6 text-muted-foreground" />
						<h1 className="text-xl font-bold">Settings</h1>
					</div>

					<Card density="compact" id="appearance">
						<CardHeader>
							<CardTitle>Appearance</CardTitle>
							<CardDescription>Customize fonts used throughout the application</CardDescription>
						</CardHeader>
						<CardContent className="space-y-6">
							<div className="space-y-1.5">
								<Label className="text-sm font-medium">UI Font Family</Label>
								<Popover open={uiFontOpen} onOpenChange={setUiFontOpen}>
									<PopoverTrigger asChild>
										<Button variant="outline" className="w-full justify-between font-normal">
											<span
												className="truncate"
												style={{
													fontFamily: fontSettings.ui_family
														? `"${fontSettings.ui_family}"`
														: undefined,
												}}
											>
												{fontSettings.ui_family || 'System Default'}
											</span>
											<ChevronsUpDown className="ml-2 h-4 w-4 shrink-0 opacity-50" />
										</Button>
									</PopoverTrigger>
									<PopoverContent
										className="w-[var(--radix-popover-trigger-width)] p-0"
										align="start"
									>
										<Command>
											<CommandInput placeholder="Search fonts..." />
											<CommandList className="max-h-48">
												<CommandEmpty>No fonts found.</CommandEmpty>
												<CommandGroup heading="System Fonts">
													<CommandItem
														value="System Default"
														onSelect={() => {
															setFontSettings((prev) => ({ ...prev, ui_family: '' }));
															setUiFontOpen(false);
														}}
													>
														<span>System Default</span>
														{!fontSettings.ui_family ? <Check className="ml-auto h-4 w-4" /> : null}
													</CommandItem>
													{systemFonts.map((font) => (
														<CommandItem
															key={font}
															value={font}
															onSelect={() => {
																setFontSettings((prev) => ({ ...prev, ui_family: font }));
																setUiFontOpen(false);
															}}
														>
															<span style={{ fontFamily: `"${font}"` }}>{font}</span>
															{fontSettings.ui_family === font ? (
																<Check className="ml-auto h-4 w-4" />
															) : null}
														</CommandItem>
													))}
												</CommandGroup>
												{fontSettings.google_fonts_enabled ? (
													<CommandGroup heading="Google Fonts">
														{googleUiFonts.map((gf) => (
															<CommandItem
																key={gf.name}
																value={`Google: ${gf.name}`}
																onSelect={() =>
																	selectGoogleFont('ui_family', gf.name, () => setUiFontOpen(false))
																}
															>
																<Globe className="h-3.5 w-3.5 shrink-0 text-muted-foreground" />
																<span style={{ fontFamily: `"${gf.name}"` }}>{gf.name}</span>
																{fontSettings.ui_family === gf.name ? (
																	<Check className="ml-auto h-4 w-4" />
																) : null}
															</CommandItem>
														))}
													</CommandGroup>
												) : null}
											</CommandList>
										</Command>
									</PopoverContent>
								</Popover>
							</div>

							<FormSlider
								label="UI Font Size"
								value={fontSettings.ui_size}
								valueLabel={`${fontSettings.ui_size}px`}
								min={10}
								max={24}
								step={1}
								onValueChange={(v) => setFontSettings((prev) => ({ ...prev, ui_size: v }))}
							/>

							<div className="space-y-1.5">
								<Label className="text-sm font-medium">Code Font Family</Label>
								<Popover open={codeFontOpen} onOpenChange={setCodeFontOpen}>
									<PopoverTrigger asChild>
										<Button variant="outline" className="w-full justify-between font-normal">
											<span
												className="truncate"
												style={{
													fontFamily: fontSettings.code_family
														? `"${fontSettings.code_family}"`
														: undefined,
												}}
											>
												{fontSettings.code_family || 'System Default'}
											</span>
											<ChevronsUpDown className="ml-2 h-4 w-4 shrink-0 opacity-50" />
										</Button>
									</PopoverTrigger>
									<PopoverContent
										className="w-[var(--radix-popover-trigger-width)] p-0"
										align="start"
									>
										<Command>
											<CommandInput placeholder="Search fonts..." />
											<CommandList className="max-h-48">
												<CommandEmpty>No fonts found.</CommandEmpty>
												<CommandGroup heading="System Monospace Fonts">
													<CommandItem
														value="System Default"
														onSelect={() => {
															setFontSettings((prev) => ({ ...prev, code_family: '' }));
															setCodeFontOpen(false);
														}}
													>
														<span>System Default</span>
														{!fontSettings.code_family ? (
															<Check className="ml-auto h-4 w-4" />
														) : null}
													</CommandItem>
													{monospaceFonts.map((font) => (
														<CommandItem
															key={font}
															value={font}
															onSelect={() => {
																setFontSettings((prev) => ({ ...prev, code_family: font }));
																setCodeFontOpen(false);
															}}
														>
															<span style={{ fontFamily: `"${font}"` }}>{font}</span>
															{fontSettings.code_family === font ? (
																<Check className="ml-auto h-4 w-4" />
															) : null}
														</CommandItem>
													))}
												</CommandGroup>
												{fontSettings.google_fonts_enabled ? (
													<CommandGroup heading="Google Fonts">
														{googleCodeFonts.map((gf) => (
															<CommandItem
																key={gf.name}
																value={`Google: ${gf.name}`}
																onSelect={() =>
																	selectGoogleFont('code_family', gf.name, () =>
																		setCodeFontOpen(false)
																	)
																}
															>
																<Globe className="h-3.5 w-3.5 shrink-0 text-muted-foreground" />
																<span style={{ fontFamily: `"${gf.name}"` }}>{gf.name}</span>
																{fontSettings.code_family === gf.name ? (
																	<Check className="ml-auto h-4 w-4" />
																) : null}
															</CommandItem>
														))}
													</CommandGroup>
												) : null}
											</CommandList>
										</Command>
									</PopoverContent>
								</Popover>
							</div>

							<FormSlider
								label="Code Font Size"
								value={fontSettings.code_size}
								valueLabel={`${fontSettings.code_size}px`}
								min={10}
								max={24}
								step={1}
								onValueChange={(v) => setFontSettings((prev) => ({ ...prev, code_size: v }))}
							/>

							<div className="space-y-3">
								<FormCheckbox
									label="Enable Google Fonts"
									checked={fontSettings.google_fonts_enabled}
									onCheckedChange={(v) =>
										setFontSettings((prev) => ({ ...prev, google_fonts_enabled: v }))
									}
								/>

								{fontSettings.google_fonts_enabled ? (
									<Alert variant="destructive">
										<AlertTriangle className="size-4" />
										<AlertTitle>Privacy Notice</AlertTitle>
										<AlertDescription>
											Google Fonts are loaded from Google's servers. Your IP address will be sent to
											Google when fonts are loaded. Only enable this if you understand and accept
											these privacy implications.
										</AlertDescription>
									</Alert>
								) : null}
							</div>

							<div className="space-y-3 rounded-lg border border-border/60 bg-muted/30 p-4">
								<p className="text-xs font-medium text-muted-foreground">Preview</p>
								<p
									style={{
										fontFamily: fontSettings.ui_family
											? `"${fontSettings.ui_family}", system-ui, sans-serif`
											: undefined,
										fontSize:
											fontSettings.ui_size !== DEFAULT_SETTINGS.font.ui_size
												? `${fontSettings.ui_size}px`
												: undefined,
									}}
								>
									The quick brown fox jumps over the lazy dog.
								</p>
								<pre
									className="rounded-md bg-muted p-2"
									style={{
										fontFamily: fontSettings.code_family
											? `"${fontSettings.code_family}", ui-monospace, monospace`
											: undefined,
										fontSize:
											fontSettings.code_size !== DEFAULT_SETTINGS.font.code_size
												? `${fontSettings.code_size}px`
												: undefined,
									}}
								>
									<code>{'const hello = "world"; // 0123456789'}</code>
								</pre>
							</div>
						</CardContent>
					</Card>

					<Card density="compact" id="data">
						<CardHeader>
							<CardTitle>Data</CardTitle>
							<CardDescription>Settings file location and reset options</CardDescription>
						</CardHeader>
						<CardContent className="space-y-4">
							{settingsFilePath ? (
								<div className="space-y-1">
									<Label className="text-xs text-muted-foreground">Settings file</Label>
									<p className="rounded-md bg-muted/50 px-3 py-2 font-mono text-xs text-muted-foreground">
										{settingsFilePath}
									</p>
								</div>
							) : null}
							<div className="space-y-2">
								<Button variant="destructive" size="sm" onClick={handleReset}>
									<RotateCcw className="h-4 w-4" />
									Reset All Settings
								</Button>
								<p className="text-xs text-muted-foreground">
									Resets all preferences including fonts and window position to defaults.
								</p>
							</div>
						</CardContent>
					</Card>
				</div>
			</main>
		</div>
	);
}

// src/routes/settings/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { toast } from 'svelte-sonner';
	import { confirm } from '@tauri-apps/plugin-dialog';
	import { Settings, Check, ChevronsUpDown, RotateCcw, Globe, AlertTriangle } from '@lucide/svelte';
	import * as Alert from '$lib/components/ui/alert/index.js';
	import * as Card from '$lib/components/ui/card/index.js';
	import * as Popover from '$lib/components/ui/popover/index.js';
	import * as Command from '$lib/components/ui/command/index.js';
	import { Button } from '$lib/components/ui/button/index.js';
	import { Label } from '$lib/components/ui/label/index.js';
	import { FormCheckbox, FormSlider } from '$lib/components/form/index.js';
	import {
		type AppSettings,
		type FontSettings,
		DEFAULT_SETTINGS,
		getSettings,
		getSystemFonts,
		getMonospaceSystemFonts,
		getSettingsFilePath,
		updateSettings,
		resetSettings,
		applyAllSettings,
	} from '$lib/services/settings.js';
	import { getGoogleFontsByCategory, loadGoogleFont } from '$lib/services/google-fonts.js';

	// State
	let fontSettings = $state<FontSettings>({ ...DEFAULT_SETTINGS.font });
	let systemFonts = $state<string[]>([]);
	let monospaceFonts = $state<string[]>([]);
	let settingsFilePath = $state('');

	// Derived: Google Fonts by category
	const googleUiFonts = getGoogleFontsByCategory('sans-serif');
	const googleCodeFonts = getGoogleFontsByCategory('monospace');

	// Combobox open states
	let uiFontOpen = $state(false);
	let codeFontOpen = $state(false);

	// Debounce timer for auto-save
	let saveTimer: ReturnType<typeof setTimeout> | undefined;

	// Build full AppSettings from current state
	const currentSettings = $derived<AppSettings>({
		font: fontSettings,
	});

	// Auto-save on settings change (300ms debounce)
	$effect(() => {
		// Access the derived value to subscribe
		const settings = currentSettings;

		clearTimeout(saveTimer);
		saveTimer = setTimeout(() => {
			updateSettings(settings)
				.then(() => applyAllSettings(settings))
				.catch(() => toast.error('Failed to save settings'));
		}, 300);
	});

	// Cleanup timer on unmount
	$effect(() => {
		return () => {
			clearTimeout(saveTimer);
		};
	});

	// Load settings and system fonts on mount
	onMount(() => {
		getSettings()
			.then((settings) => {
				fontSettings = { ...settings.font };
			})
			.catch(() => {});

		getSystemFonts()
			.then((fonts) => {
				systemFonts = fonts;
			})
			.catch(() => {});

		getMonospaceSystemFonts()
			.then((fonts) => {
				monospaceFonts = fonts;
			})
			.catch(() => {});

		getSettingsFilePath()
			.then((path) => {
				settingsFilePath = path;
			})
			.catch(() => {});
	});

	// Reset all settings
	const handleReset = async () => {
		const confirmed = await confirm(
			'This will reset all settings including fonts and window position.',
			{
				title: 'Reset All Settings',
				kind: 'warning',
				okLabel: 'Reset',
				cancelLabel: 'Cancel',
			}
		);
		if (!confirmed) return;

		const defaults = await resetSettings();
		fontSettings = { ...defaults.font };
		applyAllSettings(defaults);
		toast.success('All settings have been reset');
	};

	// Handle Google Font selection: preload it for preview
	const selectGoogleFont = (
		field: 'ui_family' | 'code_family',
		fontName: string,
		closePopover: () => void
	) => {
		loadGoogleFont(fontName);
		fontSettings = { ...fontSettings, [field]: fontName };
		closePopover();
	};
</script>

<svelte:head>
	<title>Settings - Kogu</title>
</svelte:head>

<div class="flex h-full flex-col">
	<main class="flex-1 overflow-y-auto p-6">
		<div class="mx-auto max-w-2xl space-y-6">
			<!-- Header -->
			<div class="flex items-center gap-3">
				<Settings class="h-6 w-6 text-muted-foreground" />
				<h1 class="text-xl font-bold">Settings</h1>
			</div>

			<!-- Appearance Card -->
			<Card.Root density="compact" id="appearance">
				<Card.Header>
					<Card.Title>Appearance</Card.Title>
					<Card.Description>Customize fonts used throughout the application</Card.Description>
				</Card.Header>
				<Card.Content class="space-y-6">
					<!-- UI Font Family -->
					<div class="space-y-1.5">
						<Label class="text-sm font-medium">UI Font Family</Label>
						<Popover.Root bind:open={uiFontOpen}>
							<Popover.Trigger>
								{#snippet child({ props })}
									<Button variant="outline" class="w-full justify-between font-normal" {...props}>
										<span
											class="truncate"
											style:font-family={fontSettings.ui_family
												? `"${fontSettings.ui_family}"`
												: undefined}
										>
											{fontSettings.ui_family || 'System Default'}
										</span>
										<ChevronsUpDown class="ml-2 h-4 w-4 shrink-0 opacity-50" />
									</Button>
								{/snippet}
							</Popover.Trigger>
							<Popover.Content class="w-[var(--bits-popover-anchor-width)] p-0" align="start">
								<Command.Root>
									<Command.Input placeholder="Search fonts..." />
									<Command.List class="max-h-48">
										<Command.Empty>No fonts found.</Command.Empty>
										<Command.Group heading="System Fonts">
											<Command.Item
												value="System Default"
												onSelect={() => {
													fontSettings = { ...fontSettings, ui_family: '' };
													uiFontOpen = false;
												}}
											>
												<span>System Default</span>
												{#if !fontSettings.ui_family}
													<Check class="ml-auto h-4 w-4" />
												{/if}
											</Command.Item>
											{#each systemFonts as font (font)}
												<Command.Item
													value={font}
													onSelect={() => {
														fontSettings = { ...fontSettings, ui_family: font };
														uiFontOpen = false;
													}}
												>
													<span style:font-family={`"${font}"`}>{font}</span>
													{#if fontSettings.ui_family === font}
														<Check class="ml-auto h-4 w-4" />
													{/if}
												</Command.Item>
											{/each}
										</Command.Group>
										{#if fontSettings.google_fonts_enabled}
											<Command.Group heading="Google Fonts">
												{#each googleUiFonts as gf (gf.name)}
													<Command.Item
														value={`Google: ${gf.name}`}
														onSelect={() =>
															selectGoogleFont('ui_family', gf.name, () => {
																uiFontOpen = false;
															})}
													>
														<Globe class="h-3.5 w-3.5 shrink-0 text-muted-foreground" />
														<span style:font-family={`"${gf.name}"`}>{gf.name}</span>
														{#if fontSettings.ui_family === gf.name}
															<Check class="ml-auto h-4 w-4" />
														{/if}
													</Command.Item>
												{/each}
											</Command.Group>
										{/if}
									</Command.List>
								</Command.Root>
							</Popover.Content>
						</Popover.Root>
					</div>

					<!-- UI Font Size -->
					<FormSlider
						label="UI Font Size"
						value={fontSettings.ui_size}
						valueLabel={`${fontSettings.ui_size}px`}
						min={10}
						max={24}
						step={1}
						onchange={(v) => (fontSettings = { ...fontSettings, ui_size: v })}
					/>

					<!-- Code Font Family -->
					<div class="space-y-1.5">
						<Label class="text-sm font-medium">Code Font Family</Label>
						<Popover.Root bind:open={codeFontOpen}>
							<Popover.Trigger>
								{#snippet child({ props })}
									<Button variant="outline" class="w-full justify-between font-normal" {...props}>
										<span
											class="truncate"
											style:font-family={fontSettings.code_family
												? `"${fontSettings.code_family}"`
												: undefined}
										>
											{fontSettings.code_family || 'System Default'}
										</span>
										<ChevronsUpDown class="ml-2 h-4 w-4 shrink-0 opacity-50" />
									</Button>
								{/snippet}
							</Popover.Trigger>
							<Popover.Content class="w-[var(--bits-popover-anchor-width)] p-0" align="start">
								<Command.Root>
									<Command.Input placeholder="Search fonts..." />
									<Command.List class="max-h-48">
										<Command.Empty>No fonts found.</Command.Empty>
										<Command.Group heading="System Monospace Fonts">
											<Command.Item
												value="System Default"
												onSelect={() => {
													fontSettings = { ...fontSettings, code_family: '' };
													codeFontOpen = false;
												}}
											>
												<span>System Default</span>
												{#if !fontSettings.code_family}
													<Check class="ml-auto h-4 w-4" />
												{/if}
											</Command.Item>
											{#each monospaceFonts as font (font)}
												<Command.Item
													value={font}
													onSelect={() => {
														fontSettings = { ...fontSettings, code_family: font };
														codeFontOpen = false;
													}}
												>
													<span style:font-family={`"${font}"`}>{font}</span>
													{#if fontSettings.code_family === font}
														<Check class="ml-auto h-4 w-4" />
													{/if}
												</Command.Item>
											{/each}
										</Command.Group>
										{#if fontSettings.google_fonts_enabled}
											<Command.Group heading="Google Fonts">
												{#each googleCodeFonts as gf (gf.name)}
													<Command.Item
														value={`Google: ${gf.name}`}
														onSelect={() =>
															selectGoogleFont('code_family', gf.name, () => {
																codeFontOpen = false;
															})}
													>
														<Globe class="h-3.5 w-3.5 shrink-0 text-muted-foreground" />
														<span style:font-family={`"${gf.name}"`}>{gf.name}</span>
														{#if fontSettings.code_family === gf.name}
															<Check class="ml-auto h-4 w-4" />
														{/if}
													</Command.Item>
												{/each}
											</Command.Group>
										{/if}
									</Command.List>
								</Command.Root>
							</Popover.Content>
						</Popover.Root>
					</div>

					<!-- Code Font Size -->
					<FormSlider
						label="Code Font Size"
						value={fontSettings.code_size}
						valueLabel={`${fontSettings.code_size}px`}
						min={10}
						max={24}
						step={1}
						onchange={(v) => (fontSettings = { ...fontSettings, code_size: v })}
					/>

					<!-- Google Fonts Toggle -->
					<div class="space-y-3">
						<FormCheckbox
							label="Enable Google Fonts"
							checked={fontSettings.google_fonts_enabled}
							onchange={(v) => (fontSettings = { ...fontSettings, google_fonts_enabled: v })}
						/>

						{#if fontSettings.google_fonts_enabled}
							<Alert.Root variant="destructive">
								<AlertTriangle class="size-4" />
								<Alert.Title>Privacy Notice</Alert.Title>
								<Alert.Description>
									Google Fonts are loaded from Google's servers. Your IP address will be sent to
									Google when fonts are loaded. Only enable this if you understand and accept these
									privacy implications.
								</Alert.Description>
							</Alert.Root>
						{/if}
					</div>

					<!-- Preview -->
					<div class="space-y-3 rounded-lg border border-border/60 bg-muted/30 p-4">
						<p class="text-xs font-medium text-muted-foreground">Preview</p>
						<p
							style:font-family={fontSettings.ui_family
								? `"${fontSettings.ui_family}", system-ui, sans-serif`
								: undefined}
							style:font-size={fontSettings.ui_size !== DEFAULT_SETTINGS.font.ui_size
								? `${fontSettings.ui_size}px`
								: undefined}
						>
							The quick brown fox jumps over the lazy dog.
						</p>
						<pre
							class="rounded-md bg-muted p-2"
							style:font-family={fontSettings.code_family
								? `"${fontSettings.code_family}", ui-monospace, monospace`
								: undefined}
							style:font-size={fontSettings.code_size !== DEFAULT_SETTINGS.font.code_size
								? `${fontSettings.code_size}px`
								: undefined}><code>const hello = "world"; // 0123456789</code></pre>
					</div>
				</Card.Content>
			</Card.Root>

			<!-- Data Card -->
			<Card.Root density="compact" id="data">
				<Card.Header>
					<Card.Title>Data</Card.Title>
					<Card.Description>Settings file location and reset options</Card.Description>
				</Card.Header>
				<Card.Content class="space-y-4">
					{#if settingsFilePath}
						<div class="space-y-1">
							<Label class="text-xs text-muted-foreground">Settings file</Label>
							<p class="rounded-md bg-muted/50 px-3 py-2 font-mono text-xs text-muted-foreground">
								{settingsFilePath}
							</p>
						</div>
					{/if}
					<div class="space-y-2">
						<Button variant="destructive" size="sm" onclick={handleReset}>
							<RotateCcw class="mr-2 h-4 w-4" />
							Reset All Settings
						</Button>
						<p class="text-xs text-muted-foreground">
							Resets all preferences including fonts and window position to defaults.
						</p>
					</div>
				</Card.Content>
			</Card.Root>
		</div>
	</main>
</div>
