// src/lib/components/form/form-slider.tsx
import { Label } from '@/lib/components/ui/label';
import { Slider } from '@/lib/components/ui/slider';

interface FormSliderProps {
	readonly label: string;
	readonly value?: number;
	readonly min?: number;
	readonly max?: number;
	readonly step?: number;
	readonly showValue?: boolean;
	readonly valueLabel?: string;
	readonly hint?: string;
	readonly onValueChange?: (value: number) => void;
}

export function FormSlider({
	label,
	value = 0,
	min = 0,
	max = 100,
	step = 1,
	showValue = true,
	valueLabel,
	hint,
	onValueChange,
}: FormSliderProps) {
	const displayValue = valueLabel ?? String(value);

	const handleChange = (next: readonly number[]) => {
		const first = next[0];
		if (first !== undefined) {
			onValueChange?.(first);
		}
	};

	return (
		<div className="space-y-1.5">
			<div className="flex items-center justify-between gap-2">
				<Label className="min-w-0 truncate text-sm font-medium">{label}</Label>
				{showValue ? (
					<span className="shrink-0 text-sm font-medium tabular-nums">{displayValue}</span>
				) : null}
			</div>
			<Slider value={[value]} onValueChange={handleChange} min={min} max={max} step={step} />
			{hint ? <p className="text-xs text-muted-foreground">{hint}</p> : null}
		</div>
	);
}

export type { FormSliderProps };

// src/lib/components/form/form-slider.svelte
<script lang="ts">
	import { Label } from '$lib/components/ui/label/index.js';
	import { Slider } from '$lib/components/ui/slider/index.js';

	interface Props {
		label: string;
		value?: number;
		min?: number;
		max?: number;
		step?: number;
		showValue?: boolean;
		valueLabel?: string;
		hint?: string;
		onchange?: (value: number) => void;
	}

	let {
		label,
		value = $bindable(0),
		min = 0,
		max = 100,
		step = 1,
		showValue = true,
		valueLabel,
		hint,
		onchange,
	}: Props = $props();

	const displayValue = $derived(valueLabel ?? String(value));
</script>

<div class="space-y-1.5">
	<div class="flex items-center justify-between gap-2">
		<Label class="min-w-0 truncate text-sm font-medium">{label}</Label>
		{#if showValue}
			<span class="shrink-0 text-sm font-medium tabular-nums">{displayValue}</span>
		{/if}
	</div>
	<Slider type="single" bind:value {min} {max} {step} onValueChange={(v) => onchange?.(v)} />
	{#if hint}
		<p class="text-xs text-muted-foreground">{hint}</p>
	{/if}
</div>
