// src/lib/components/form/form-checkbox-group.tsx
import type { ReactNode } from 'react';

import { cn } from '@/lib/utils';

interface FormCheckboxGroupProps {
	readonly className?: string;
	readonly children?: ReactNode;
}

export function FormCheckboxGroup({ className, children }: FormCheckboxGroupProps) {
	return <fieldset className={cn('space-y-1.5 border-0 p-0', className)}>{children}</fieldset>;
}

export type { FormCheckboxGroupProps };

// src/lib/components/form/form-checkbox-group.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import { cn } from '$lib/utils.js';

	interface Props {
		class?: string;
		children?: Snippet;
	}

	let { class: className, children }: Props = $props();
</script>

<div class={cn('space-y-1.5', className)} role="group">
	{@render children?.()}
</div>
