// src/routes/bcrypt-generator.tsx
import { createFileRoute } from '@tanstack/react-router';
import { useEffect, useRef, useState } from 'react';
import { Check, Hash, ShieldCheck, X } from 'lucide-react';
import { toast } from 'sonner';

import { ActionButton, CopyButton } from '@/lib/components/action';
import { FormInfo, FormInput, FormMode, FormSection, FormSlider } from '@/lib/components/form';
import { SectionHeader } from '@/lib/components/layout';
import { ToolShell } from '@/lib/components/shell';
import { EmptyState, ErrorDisplay, LoadingOverlay, StatItem } from '@/lib/components/status';
import { Card, CardContent, CardHeader, CardTitle } from '@/lib/components/ui/card';
import {
	type BcryptCostInfo,
	type BcryptHashResult,
	type BcryptVerifyResult,
	cancelWorkerOperation,
	DEFAULT_BCRYPT_COST,
	generateBcryptHash,
	getBcryptCostInfo,
	MAX_BCRYPT_COST,
	MIN_BCRYPT_COST,
	verifyBcryptHash,
} from '@/lib/services/generators';

type ActiveTab = 'generate' | 'verify';

const formatElapsedTime = (ms: number): string =>
	ms < 1000 ? `${Math.round(ms)}ms` : `${(ms / 1000).toFixed(1)}s`;

export const Route = createFileRoute('/bcrypt-generator')({
	component: BcryptGeneratorPage,
});

function BcryptGeneratorPage() {
	const [password, setPassword] = useState('');
	const [cost, setCost] = useState(DEFAULT_BCRYPT_COST);
	const [hashResult, setHashResult] = useState<BcryptHashResult | null>(null);
	const [isGenerating, setIsGenerating] = useState(false);
	const [generateError, setGenerateError] = useState<string | null>(null);
	const generateCancelledRef = useRef(false);

	const [verifyPassword, setVerifyPassword] = useState('');
	const [verifyHash, setVerifyHash] = useState('');
	const [verifyResult, setVerifyResult] = useState<BcryptVerifyResult | null>(null);
	const [isVerifying, setIsVerifying] = useState(false);
	const [verifyError, setVerifyError] = useState<string | null>(null);
	const verifyCancelledRef = useRef(false);

	const [showOptions, setShowOptions] = useState(true);
	const [costInfo, setCostInfo] = useState<BcryptCostInfo | null>(null);
	const [activeTab, setActiveTab] = useState<ActiveTab>('generate');
	const [flashCounter, setFlashCounter] = useState(0);

	const [elapsedMs, setElapsedMs] = useState(0);
	const timerIntervalRef = useRef<ReturnType<typeof setInterval> | null>(null);

	useEffect(() => {
		document.title = 'BCrypt Generator — Kogu';
	}, []);

	useEffect(() => {
		getBcryptCostInfo(cost)
			.then(setCostInfo)
			.catch(() => setCostInfo(null));
	}, [cost]);

	const startTimer = () => {
		setElapsedMs(0);
		timerIntervalRef.current = setInterval(() => {
			setElapsedMs((prev) => prev + 100);
		}, 100);
	};

	const stopTimer = () => {
		if (timerIntervalRef.current) {
			clearInterval(timerIntervalRef.current);
			timerIntervalRef.current = null;
		}
	};

	const canGenerate = password.trim().length > 0;
	const canVerify = verifyPassword.trim().length > 0 && verifyHash.trim().length > 0;

	const estimatedTime = (() => {
		if (!costInfo) return 'Unknown';
		const ms = costInfo.estimated_time_ms;
		if (ms < 1000) return `~${Math.round(ms)}ms`;
		return `~${(ms / 1000).toFixed(1)}s`;
	})();

	const elapsedTimeDisplay = formatElapsedTime(elapsedMs);

	const handleGenerate = async () => {
		if (!canGenerate) return;
		setIsGenerating(true);
		generateCancelledRef.current = false;
		setGenerateError(null);
		setHashResult(null);
		startTimer();

		try {
			const result = await generateBcryptHash(password, cost);
			if (!generateCancelledRef.current) {
				setHashResult(result);
				setFlashCounter((c) => c + 1);
				toast.success('BCrypt hash generated successfully');
			}
		} catch (e) {
			if (!generateCancelledRef.current) {
				const message = e instanceof Error ? e.message : String(e);
				setGenerateError(message);
				toast.error('Failed to generate hash', { description: message });
			}
		} finally {
			stopTimer();
			setIsGenerating(false);
		}
	};

	const handleCancelGenerate = async () => {
		generateCancelledRef.current = true;
		await cancelWorkerOperation();
		stopTimer();
		setIsGenerating(false);
		toast.info('Hash generation cancelled');
	};

	const handleVerify = async () => {
		if (!canVerify) return;
		setIsVerifying(true);
		verifyCancelledRef.current = false;
		setVerifyError(null);
		setVerifyResult(null);
		startTimer();

		try {
			const result = await verifyBcryptHash(verifyPassword, verifyHash);
			if (!verifyCancelledRef.current) {
				setVerifyResult(result);
				if (result.valid) {
					toast.success('Password matches the hash');
				} else {
					toast.error('Password does not match the hash');
				}
			}
		} catch (e) {
			if (!verifyCancelledRef.current) {
				const message = e instanceof Error ? e.message : String(e);
				setVerifyError(message);
				toast.error('Verification failed', { description: message });
			}
		} finally {
			stopTimer();
			setIsVerifying(false);
		}
	};

	const handleCancelVerify = async () => {
		verifyCancelledRef.current = true;
		await cancelWorkerOperation();
		stopTimer();
		setIsVerifying(false);
		toast.info('Verification cancelled');
	};

	const handleClearGenerate = () => {
		setPassword('');
		setHashResult(null);
		setGenerateError(null);
	};

	const handleClearVerify = () => {
		setVerifyPassword('');
		setVerifyHash('');
		setVerifyResult(null);
		setVerifyError(null);
	};

	const valid: boolean | null =
		activeTab === 'generate'
			? hashResult
				? true
				: null
			: verifyResult
				? verifyResult.valid
				: null;

	return (
		<ToolShell
			valid={valid}
			showRail={showOptions}
			onShowRailChange={setShowOptions}
			statusContent={
				activeTab === 'generate' && hashResult ? (
					<>
						<StatItem label="Cost" value={hashResult.cost} />
						<StatItem label="Algorithm" value="$2b$" />
					</>
				) : activeTab === 'verify' && verifyResult ? (
					<span className="flex items-center gap-1">
						{verifyResult.valid ? (
							<>
								<Check className="h-3 w-3 text-success" />
								<span className="text-success">Valid</span>
							</>
						) : (
							<>
								<X className="h-3 w-3 text-destructive" />
								<span className="text-destructive">Invalid</span>
							</>
						)}
					</span>
				) : null
			}
			rail={
				<>
					<FormSection title="Mode">
						<FormMode
							value={activeTab}
							onValueChange={setActiveTab}
							options={[
								{ value: 'generate', label: 'Generate', icon: Hash },
								{ value: 'verify', label: 'Verify', icon: ShieldCheck },
							]}
						/>
					</FormSection>

					{activeTab === 'generate' ? (
						<>
							<FormSection title="Password">
								<FormInput
									label="Password"
									type="password"
									showToggle
									value={password}
									onValueChange={setPassword}
									placeholder="Enter password to hash..."
									size="compact"
								/>
							</FormSection>

							<FormSection title="Cost Factor">
								<FormSlider
									label="Cost"
									value={cost}
									onValueChange={setCost}
									min={MIN_BCRYPT_COST}
									max={MAX_BCRYPT_COST}
									step={1}
									valueLabel={`${cost} (${costInfo?.security_level ?? '...'})`}
									hint={`Estimated time: ${estimatedTime}`}
									size="compact"
								/>
							</FormSection>

							<FormSection title="Actions">
								<div className="space-y-2">
									<ActionButton
										label="Generate Hash"
										icon={Hash}
										loading={isGenerating}
										loadingLabel="Generating..."
										disabled={!canGenerate}
										shortcut
										onClick={handleGenerate}
									/>
									{hashResult || password ? (
										<ActionButton label="Clear" variant="outline" onClick={handleClearGenerate} />
									) : null}
								</div>
							</FormSection>
						</>
					) : (
						<>
							<FormSection title="Password">
								<FormInput
									label="Password"
									type="password"
									showToggle
									value={verifyPassword}
									onValueChange={setVerifyPassword}
									placeholder="Enter password to verify..."
									size="compact"
								/>
							</FormSection>

							<FormSection title="Hash">
								<FormInput
									label="BCrypt Hash"
									value={verifyHash}
									onValueChange={setVerifyHash}
									placeholder="$2b$10$..."
									size="compact"
								/>
							</FormSection>

							<FormSection title="Actions">
								<div className="space-y-2">
									<ActionButton
										label="Verify Hash"
										icon={ShieldCheck}
										loading={isVerifying}
										loadingLabel="Verifying..."
										disabled={!canVerify}
										shortcut
										onClick={handleVerify}
									/>
									{verifyResult || verifyPassword || verifyHash ? (
										<ActionButton label="Clear" variant="outline" onClick={handleClearVerify} />
									) : null}
								</div>
							</FormSection>
						</>
					)}

					<FormSection title="About BCrypt">
						<FormInfo>
							<ul className="list-inside list-disc space-y-0.5">
								<li>Password hashing algorithm</li>
								<li>Salted and adaptive</li>
								<li>Cost factor controls security/speed tradeoff</li>
								<li>Recommended cost: 10-12 for most use cases</li>
							</ul>
						</FormInfo>
					</FormSection>

					<FormSection title="Cost Recommendations">
						<FormInfo showIcon={false}>
							<div className="space-y-0.5">
								<div className="flex justify-between">
									<span>4-7:</span>
									<span className="text-warning">Development only</span>
								</div>
								<div className="flex justify-between">
									<span>8-9:</span>
									<span>Low security</span>
								</div>
								<div className="flex justify-between">
									<span>10-11:</span>
									<span className="text-success">Standard</span>
								</div>
								<div className="flex justify-between">
									<span>12-13:</span>
									<span>High security</span>
								</div>
								<div className="flex justify-between">
									<span>14+:</span>
									<span>Very high security</span>
								</div>
							</div>
						</FormInfo>
					</FormSection>
				</>
			}
		>
			<div className="relative flex h-full flex-col overflow-hidden">
				<LoadingOverlay
					show={isGenerating || isVerifying}
					title={isGenerating ? 'Generating Hash...' : 'Verifying Hash...'}
					message="BCrypt computation in progress"
					estimatedTime={estimatedTime}
					elapsedTime={elapsedTimeDisplay}
					onCancel={isGenerating ? handleCancelGenerate : handleCancelVerify}
				/>
				<SectionHeader
					title={activeTab === 'generate' ? 'Generated Hash' : 'Verification Result'}
				/>

				<div className="flex-1 overflow-auto p-4">
					{activeTab === 'generate' ? (
						hashResult ? (
							<div key={flashCounter} className="animate-flash-success space-y-4 rounded-md">
								<Card density="compact">
									<CardHeader className="flex flex-row items-center justify-between space-y-0 pb-3">
										<CardTitle className="text-sm font-medium">BCrypt Hash</CardTitle>
										<CopyButton
											text={hashResult.hash}
											toastLabel="Hash"
											size="sm"
											showLabel
											className="h-7"
										/>
									</CardHeader>
									<CardContent>
										<code className="block break-all rounded bg-muted p-3 font-mono text-sm">
											{hashResult.hash}
										</code>
									</CardContent>
								</Card>

								<Card density="compact">
									<CardHeader className="pb-3">
										<CardTitle className="text-sm font-medium">Hash Details</CardTitle>
									</CardHeader>
									<CardContent>
										<div className="space-y-2 text-sm">
											<div className="flex justify-between">
												<span className="text-muted-foreground">Algorithm</span>
												<span className="font-mono">${hashResult.algorithm}$</span>
											</div>
											<div className="flex justify-between">
												<span className="text-muted-foreground">Cost Factor</span>
												<span className="font-mono">{hashResult.cost}</span>
											</div>
											<div className="flex justify-between">
												<span className="text-muted-foreground">Security Level</span>
												<span>{costInfo?.security_level ?? 'Unknown'}</span>
											</div>
											<div className="flex justify-between">
												<span className="text-muted-foreground">Hash Length</span>
												<span className="font-mono">{hashResult.hash.length} chars</span>
											</div>
										</div>
									</CardContent>
								</Card>
							</div>
						) : generateError ? (
							<ErrorDisplay variant="centered" message={generateError} />
						) : (
							<EmptyState icon={Hash} title="Enter a password and generate a BCrypt hash" />
						)
					) : verifyResult ? (
						<div className="space-y-4">
							<div
								className={`rounded-lg border p-6 ${
									verifyResult.valid
										? 'border-success/30 bg-success/10'
										: 'border-destructive/30 bg-destructive/10'
								}`}
							>
								<div className="flex items-center justify-center gap-3">
									{verifyResult.valid ? (
										<>
											<Check className="h-8 w-8 text-success" />
											<div className="text-center">
												<p className="text-lg font-semibold text-success">Password Valid</p>
												<p className="text-sm text-muted-foreground">
													The password matches the hash
												</p>
											</div>
										</>
									) : (
										<>
											<X className="h-8 w-8 text-destructive" />
											<div className="text-center">
												<p className="text-lg font-semibold text-destructive">Password Invalid</p>
												<p className="text-sm text-muted-foreground">
													The password does not match the hash
												</p>
											</div>
										</>
									)}
								</div>
							</div>
						</div>
					) : verifyError ? (
						<ErrorDisplay variant="centered" message={verifyError} />
					) : (
						<EmptyState icon={ShieldCheck} title="Enter a password and hash to verify" />
					)}
				</div>
			</div>
		</ToolShell>
	);
}

// src/routes/bcrypt-generator/+page.svelte
<script lang="ts">
	import { Check, Hash, ShieldCheck, X } from '@lucide/svelte';
	import { toast } from 'svelte-sonner';
	import { ActionButton, CopyButton } from '$lib/components/action';
	import { FormInfo, FormInput, FormMode, FormSection, FormSlider } from '$lib/components/form';
	import { SectionHeader } from '$lib/components/layout';
	import { ToolShell } from '$lib/components/shell';
	import { EmptyState, ErrorDisplay, LoadingOverlay, StatItem } from '$lib/components/status';
	import * as Card from '$lib/components/ui/card';
	import {
		type BcryptCostInfo,
		type BcryptHashResult,
		type BcryptVerifyResult,
		cancelWorkerOperation,
		DEFAULT_BCRYPT_COST,
		generateBcryptHash,
		getBcryptCostInfo,
		MAX_BCRYPT_COST,
		MIN_BCRYPT_COST,
		verifyBcryptHash,
	} from '$lib/services/generators.js';

	// State - Generate tab
	let password = $state('');
	let cost = $state(DEFAULT_BCRYPT_COST);
	let hashResult = $state<BcryptHashResult | null>(null);
	let isGenerating = $state(false);
	let generateError = $state<string | null>(null);
	let generateCancelled = $state(false);

	// State - Verify tab
	let verifyPassword = $state('');
	let verifyHash = $state('');
	let verifyResult = $state<BcryptVerifyResult | null>(null);
	let isVerifying = $state(false);
	let verifyError = $state<string | null>(null);
	let verifyCancelled = $state(false);

	// UI state
	let showOptions = $state(true);
	let costInfo = $state<BcryptCostInfo | null>(null);
	let activeTab = $state<'generate' | 'verify'>('generate');

	// Elapsed time tracking
	let elapsedMs = $state(0);
	let timerInterval = $state<ReturnType<typeof setInterval> | null>(null);

	const startTimer = () => {
		elapsedMs = 0;
		timerInterval = setInterval(() => {
			elapsedMs += 100;
		}, 100);
	};

	const stopTimer = () => {
		if (timerInterval) {
			clearInterval(timerInterval);
			timerInterval = null;
		}
	};

	const formatElapsedTime = (ms: number): string => {
		if (ms < 1000) return `${Math.round(ms)}ms`;
		return `${(ms / 1000).toFixed(1)}s`;
	};

	// Load cost info
	$effect(() => {
		getBcryptCostInfo(cost)
			.then((info) => {
				costInfo = info;
			})
			.catch(() => {
				costInfo = null;
			});
	});

	// Derived
	const canGenerate = $derived(password.trim().length > 0);
	const canVerify = $derived(verifyPassword.trim().length > 0 && verifyHash.trim().length > 0);

	const estimatedTime = $derived.by(() => {
		if (!costInfo) return 'Unknown';
		const ms = costInfo.estimated_time_ms;
		if (ms < 1000) return `~${Math.round(ms)}ms`;
		return `~${(ms / 1000).toFixed(1)}s`;
	});

	const elapsedTimeDisplay = $derived(formatElapsedTime(elapsedMs));

	// Handlers
	const handleGenerate = async () => {
		if (!canGenerate) return;

		isGenerating = true;
		generateCancelled = false;
		generateError = null;
		hashResult = null;
		startTimer();

		try {
			const result = await generateBcryptHash(password, cost);
			if (!generateCancelled) {
				hashResult = result;
				toast.success('BCrypt hash generated successfully');
			}
		} catch (e) {
			if (!generateCancelled) {
				generateError = e instanceof Error ? e.message : String(e);
				toast.error('Failed to generate hash', { description: generateError });
			}
		} finally {
			stopTimer();
			isGenerating = false;
		}
	};

	const handleCancelGenerate = async () => {
		generateCancelled = true;
		await cancelWorkerOperation();
		stopTimer();
		isGenerating = false;
		toast.info('Hash generation cancelled');
	};

	const handleVerify = async () => {
		if (!canVerify) return;

		isVerifying = true;
		verifyCancelled = false;
		verifyError = null;
		verifyResult = null;
		startTimer();

		try {
			const result = await verifyBcryptHash(verifyPassword, verifyHash);
			if (!verifyCancelled) {
				verifyResult = result;
				if (result.valid) {
					toast.success('Password matches the hash');
				} else {
					toast.error('Password does not match the hash');
				}
			}
		} catch (e) {
			if (!verifyCancelled) {
				verifyError = e instanceof Error ? e.message : String(e);
				toast.error('Verification failed', { description: verifyError });
			}
		} finally {
			stopTimer();
			isVerifying = false;
		}
	};

	const handleCancelVerify = async () => {
		verifyCancelled = true;
		await cancelWorkerOperation();
		stopTimer();
		isVerifying = false;
		toast.info('Verification cancelled');
	};

	const handleClearGenerate = () => {
		password = '';
		hashResult = null;
		generateError = null;
	};

	const handleClearVerify = () => {
		verifyPassword = '';
		verifyHash = '';
		verifyResult = null;
		verifyError = null;
	};
</script>

<svelte:head>
	<title>BCrypt Generator - Kogu</title>
</svelte:head>

<ToolShell
	valid={activeTab === 'generate'
		? hashResult
			? true
			: null
		: verifyResult
			? verifyResult.valid
			: null}
	bind:showRail={showOptions}
>
	{#snippet statusContent()}
		{#if activeTab === 'generate' && hashResult}
			<StatItem label="Cost" value={hashResult.cost} />
			<StatItem label="Algorithm" value="$2b$" />
		{:else if activeTab === 'verify' && verifyResult}
			<span class="flex items-center gap-1">
				{#if verifyResult.valid}
					<Check class="h-3 w-3 text-success" />
					<span class="text-success">Valid</span>
				{:else}
					<X class="h-3 w-3 text-destructive" />
					<span class="text-destructive">Invalid</span>
				{/if}
			</span>
		{/if}
	{/snippet}

	{#snippet rail()}
		<FormSection title="Mode">
			<FormMode
				value={activeTab}
				onchange={(v) => (activeTab = v as 'generate' | 'verify')}
				options={[
					{ value: 'generate', label: 'Generate', icon: Hash },
					{ value: 'verify', label: 'Verify', icon: ShieldCheck },
				]}
			/>
		</FormSection>

		{#if activeTab === 'generate'}
			<FormSection title="Password">
				<FormInput
					label="Password"
					type="password"
					showToggle
					bind:value={password}
					placeholder="Enter password to hash..."
				/>
			</FormSection>

			<FormSection title="Cost Factor">
				<FormSlider
					label="Cost"
					bind:value={cost}
					min={MIN_BCRYPT_COST}
					max={MAX_BCRYPT_COST}
					step={1}
					valueLabel={`${cost} (${costInfo?.security_level ?? '...'})`}
					hint={`Estimated time: ${estimatedTime}`}
				/>
			</FormSection>

			<FormSection title="Actions">
				<div class="space-y-2">
					<ActionButton
						label="Generate Hash"
						icon={Hash}
						loading={isGenerating}
						loadingLabel="Generating..."
						disabled={!canGenerate}
						shortcut
						onclick={handleGenerate}
					/>
					{#if hashResult || password}
						<ActionButton label="Clear" variant="outline" onclick={handleClearGenerate} />
					{/if}
				</div>
			</FormSection>
		{:else}
			<FormSection title="Password">
				<FormInput
					label="Password"
					type="password"
					showToggle
					bind:value={verifyPassword}
					placeholder="Enter password to verify..."
				/>
			</FormSection>

			<FormSection title="Hash">
				<FormInput label="BCrypt Hash" bind:value={verifyHash} placeholder="$2b$10$..." />
			</FormSection>

			<FormSection title="Actions">
				<div class="space-y-2">
					<ActionButton
						label="Verify Hash"
						icon={ShieldCheck}
						loading={isVerifying}
						loadingLabel="Verifying..."
						disabled={!canVerify}
						shortcut
						onclick={handleVerify}
					/>
					{#if verifyResult || verifyPassword || verifyHash}
						<ActionButton label="Clear" variant="outline" onclick={handleClearVerify} />
					{/if}
				</div>
			</FormSection>
		{/if}

		<FormSection title="About BCrypt">
			<FormInfo>
				<ul class="list-inside list-disc space-y-0.5">
					<li>Password hashing algorithm</li>
					<li>Salted and adaptive</li>
					<li>Cost factor controls security/speed tradeoff</li>
					<li>Recommended cost: 10-12 for most use cases</li>
				</ul>
			</FormInfo>
		</FormSection>

		<FormSection title="Cost Recommendations">
			<FormInfo showIcon={false}>
				<div class="space-y-0.5">
					<div class="flex justify-between">
						<span>4-7:</span>
						<span class="text-warning">Development only</span>
					</div>
					<div class="flex justify-between">
						<span>8-9:</span>
						<span>Low security</span>
					</div>
					<div class="flex justify-between">
						<span>10-11:</span>
						<span class="text-success">Standard</span>
					</div>
					<div class="flex justify-between">
						<span>12-13:</span>
						<span>High security</span>
					</div>
					<div class="flex justify-between">
						<span>14+:</span>
						<span>Very high security</span>
					</div>
				</div>
			</FormInfo>
		</FormSection>
	{/snippet}

	<!-- Results Panel -->
	<div class="relative flex h-full flex-col overflow-hidden">
		<LoadingOverlay
			show={isGenerating || isVerifying}
			title={isGenerating ? 'Generating Hash...' : 'Verifying Hash...'}
			message="BCrypt computation in progress"
			{estimatedTime}
			elapsedTime={elapsedTimeDisplay}
			oncancel={isGenerating ? handleCancelGenerate : handleCancelVerify}
		/>
		<SectionHeader title={activeTab === 'generate' ? 'Generated Hash' : 'Verification Result'} />

		<div class="flex-1 overflow-auto p-4">
			{#if activeTab === 'generate'}
				{#if hashResult}
					<div class="space-y-4">
						<Card.Root density="compact">
							<Card.Header class="flex flex-row items-center justify-between space-y-0 pb-3">
								<Card.Title class="text-sm font-medium">BCrypt Hash</Card.Title>
								<CopyButton
									text={hashResult.hash}
									toastLabel="Hash"
									size="sm"
									showLabel
									class="h-7"
								/>
							</Card.Header>
							<Card.Content>
								<code class="block break-all rounded bg-muted p-3 font-mono text-sm">
									{hashResult.hash}
								</code>
							</Card.Content>
						</Card.Root>

						<Card.Root density="compact">
							<Card.Header class="pb-3">
								<Card.Title class="text-sm font-medium">Hash Details</Card.Title>
							</Card.Header>
							<Card.Content>
								<div class="space-y-2 text-sm">
									<div class="flex justify-between">
										<span class="text-muted-foreground">Algorithm</span>
										<span class="font-mono">${hashResult.algorithm}$</span>
									</div>
									<div class="flex justify-between">
										<span class="text-muted-foreground">Cost Factor</span>
										<span class="font-mono">{hashResult.cost}</span>
									</div>
									<div class="flex justify-between">
										<span class="text-muted-foreground">Security Level</span>
										<span>{costInfo?.security_level ?? 'Unknown'}</span>
									</div>
									<div class="flex justify-between">
										<span class="text-muted-foreground">Hash Length</span>
										<span class="font-mono">{hashResult.hash.length} chars</span>
									</div>
								</div>
							</Card.Content>
						</Card.Root>
					</div>
				{:else if generateError}
					<ErrorDisplay variant="centered" message={generateError} />
				{:else}
					<EmptyState icon={Hash} title="Enter a password and generate a BCrypt hash" />
				{/if}
			{:else if verifyResult}
				<div class="space-y-4">
					<!-- Verification Result -->
					<div
						class={`rounded-lg border p-6 ${verifyResult.valid ? 'border-success/30 bg-success/10' : 'border-destructive/30 bg-destructive/10'}`}
					>
						<div class="flex items-center justify-center gap-3">
							{#if verifyResult.valid}
								<Check class="h-8 w-8 text-success" />
								<div class="text-center">
									<p class="text-lg font-semibold text-success">Password Valid</p>
									<p class="text-sm text-muted-foreground">The password matches the hash</p>
								</div>
							{:else}
								<X class="h-8 w-8 text-destructive" />
								<div class="text-center">
									<p class="text-lg font-semibold text-destructive">Password Invalid</p>
									<p class="text-sm text-muted-foreground">The password does not match the hash</p>
								</div>
							{/if}
						</div>
					</div>
				</div>
			{:else if verifyError}
				<ErrorDisplay variant="centered" message={verifyError} />
			{:else}
				<EmptyState icon={ShieldCheck} title="Enter a password and hash to verify" />
			{/if}
		</div>
	</div>
</ToolShell>
