// src/lib/components/formatter-tabs/xml/compare-tab.tsx
import { useCallback, useState } from 'react';

import { FormCheckbox, FormInput } from '@/lib/components/form';
import { CompareTab as CompareTabTemplate } from '@/lib/components/template';
import type { GenericDiffItem } from '@/lib/constants/diff';
import { findXmlDifferences, parseXml, type XmlDiffOptions } from '@/lib/services/xml-diff';
import { pasteFromClipboard } from '@/lib/utils/file-operations';

interface TabStats {
	readonly input: string;
	readonly valid: boolean | null;
	readonly error: string;
}

interface CompareTabProps {
	readonly input: string;
	readonly onInputChange: (value: string) => void;
	readonly onStatsChange?: (stats: TabStats) => void;
}

export function CompareTab({ input, onInputChange, onStatsChange }: CompareTabProps) {
	const [compareIgnoreWhitespace, setCompareIgnoreWhitespace] = useState<boolean>(true);
	const [compareIgnoreComments, setCompareIgnoreComments] = useState<boolean>(false);
	const [compareIgnoreCase, setCompareIgnoreCase] = useState<boolean>(false);
	const [compareIgnoreNamespaces, setCompareIgnoreNamespaces] = useState<boolean>(false);
	const [compareIgnoreAttributes, setCompareIgnoreAttributes] = useState<string>('');

	const ignoredAttributesList = compareIgnoreAttributes
		.split(',')
		.map((a) => a.trim())
		.filter(Boolean);

	const diffOptions: XmlDiffOptions = {
		ignoreWhitespace: compareIgnoreWhitespace,
		ignoreComments: compareIgnoreComments,
		ignoreCase: compareIgnoreCase,
		ignoreNamespaces: compareIgnoreNamespaces,
		ignoreAttributes: ignoredAttributesList,
	};

	const validate = useCallback((value: string): { valid: boolean | null } => {
		if (!value.trim()) return { valid: null };
		return { valid: parseXml(value) !== null };
	}, []);

	const compare = useCallback(
		(input1: string, input2: string): GenericDiffItem[] =>
			findXmlDifferences(input1, input2, diffOptions),
		[diffOptions]
	);

	return (
		<CompareTabTemplate
			editorMode="xml"
			input={input}
			onInputChange={onInputChange}
			placeholder1="Original XML..."
			placeholder2="Modified XML..."
			validate={validate}
			compare={compare}
			onStatsChange={onStatsChange}
			pasteFromClipboard={pasteFromClipboard}
			renderComparisonOptions={() => (
				<>
					<FormCheckbox
						label="Ignore whitespace"
						checked={compareIgnoreWhitespace}
						onCheckedChange={setCompareIgnoreWhitespace}
					/>
					<FormCheckbox
						label="Ignore comments"
						checked={compareIgnoreComments}
						onCheckedChange={setCompareIgnoreComments}
					/>
				</>
			)}
			renderAdvancedOptions={() => (
				<>
					<FormCheckbox
						label="Ignore case"
						checked={compareIgnoreCase}
						onCheckedChange={setCompareIgnoreCase}
					/>
					<FormCheckbox
						label="Ignore namespaces"
						checked={compareIgnoreNamespaces}
						onCheckedChange={setCompareIgnoreNamespaces}
					/>
					<FormInput
						label="Ignore Attributes"
						value={compareIgnoreAttributes}
						onValueChange={setCompareIgnoreAttributes}
						placeholder="attr1, attr2, attr3"
						size="compact"
						hint="Comma-separated list of attributes to ignore"
					/>
				</>
			)}
		/>
	);
}

export type { CompareTabProps };

// src/routes/xml-formatter/tabs/compare-tab.svelte
<script lang="ts">
	import { FormCheckbox, FormInput } from '$lib/components/form';
	import { CompareTab } from '$lib/components/template';
	import type { GenericDiffItem } from '$lib/constants/diff.js';
	import { findXmlDifferences, parseXml, type XmlDiffOptions } from '$lib/services/xml-diff.js';
	import { pasteFromClipboard } from '../utils.js';

	interface Props {
		input: string;
		onInputChange: (value: string) => void;
		onStatsChange?: (stats: { input: string; valid: boolean | null; error: string }) => void;
	}

	let { input, onInputChange, onStatsChange }: Props = $props();

	// Options state
	let compareIgnoreWhitespace = $state(true);
	let compareIgnoreComments = $state(false);
	let compareIgnoreCase = $state(false);
	let compareIgnoreNamespaces = $state(false);
	let compareIgnoreAttributes = $state('');

	// Parse ignored attributes from comma-separated string
	const ignoredAttributesList = $derived(
		compareIgnoreAttributes
			.split(',')
			.map((a) => a.trim())
			.filter(Boolean)
	);

	// Diff options object
	const diffOptions = $derived<XmlDiffOptions>({
		ignoreWhitespace: compareIgnoreWhitespace,
		ignoreComments: compareIgnoreComments,
		ignoreCase: compareIgnoreCase,
		ignoreNamespaces: compareIgnoreNamespaces,
		ignoreAttributes: ignoredAttributesList,
	});

	// Validation function
	const validate = (input: string) => {
		if (!input.trim()) return { valid: null as boolean | null };
		return { valid: parseXml(input) !== null };
	};

	// Compare function
	const compare = (input1: string, input2: string): GenericDiffItem[] => {
		return findXmlDifferences(input1, input2, diffOptions);
	};
</script>

<CompareTab
	editorMode="xml"
	{input}
	{onInputChange}
	placeholder1="Original XML..."
	placeholder2="Modified XML..."
	{validate}
	{compare}
	{onStatsChange}
	{pasteFromClipboard}
>
	{#snippet comparisonOptions()}
		<FormCheckbox label="Ignore whitespace" bind:checked={compareIgnoreWhitespace} />
		<FormCheckbox label="Ignore comments" bind:checked={compareIgnoreComments} />
	{/snippet}

	{#snippet advancedOptions()}
		<FormCheckbox label="Ignore case" bind:checked={compareIgnoreCase} />
		<FormCheckbox label="Ignore namespaces" bind:checked={compareIgnoreNamespaces} />
		<FormInput
			label="Ignore Attributes"
			bind:value={compareIgnoreAttributes}
			placeholder="attr1, attr2, attr3"
			size="compact"
			hint="Comma-separated list of attributes to ignore"
		/>
	{/snippet}
</CompareTab>
