// src/routes/json-formatter.tsx
import { createFileRoute } from '@tanstack/react-router';

import {
	CompareTab,
	ConvertTab,
	FormatTab,
	GenerateTab,
	QueryTab,
	SchemaTab,
} from '@/lib/components/formatter-tabs/json';
import { StatItem } from '@/lib/components/status';
import { TabbedFormatterPage } from '@/lib/components/template';
import { calculateJsonStats, type JsonStats } from '@/lib/services/formatters';

export const Route = createFileRoute('/json-formatter')({
	component: JsonFormatterPage,
});

function JsonFormatterPage() {
	return (
		<TabbedFormatterPage<JsonStats>
			title="JSON Formatter"
			calculateStats={calculateJsonStats}
			persistKey="json-formatter"
			renderStatusContent={(liveStats) =>
				liveStats ? (
					<>
						<StatItem label="Keys" value={liveStats.keys} />
						<StatItem label="Values" value={liveStats.values} />
						<StatItem label="Depth" value={liveStats.depth} />
						<StatItem label="Size" value={liveStats.size} />
					</>
				) : null
			}
			renderTabContent={({ tab, input, onInputChange, onStatsChange }) => {
				switch (tab) {
					case 'format':
						return (
							<FormatTab
								input={input}
								onInputChange={onInputChange}
								onStatsChange={onStatsChange}
							/>
						);
					case 'query':
						return (
							<QueryTab input={input} onInputChange={onInputChange} onStatsChange={onStatsChange} />
						);
					case 'compare':
						return (
							<CompareTab
								input={input}
								onInputChange={onInputChange}
								onStatsChange={onStatsChange}
							/>
						);
					case 'convert':
						return (
							<ConvertTab
								input={input}
								onInputChange={onInputChange}
								onStatsChange={onStatsChange}
							/>
						);
					case 'schema':
						return (
							<SchemaTab
								input={input}
								onInputChange={onInputChange}
								onStatsChange={onStatsChange}
							/>
						);
					case 'generate':
						return (
							<GenerateTab
								input={input}
								onInputChange={onInputChange}
								onStatsChange={onStatsChange}
							/>
						);
					default:
						return null;
				}
			}}
		/>
	);
}

// src/routes/json-formatter/+page.svelte
<script lang="ts">
	
	import { ArrowRightLeft, CodeXml, FileCheck, GitCompare, Play, Search } from '@lucide/svelte';
import { FormatterPage } from '$lib/components/tool/index.js';
	import {
		calculateJsonStats,
		JSON_FORMAT_INFO,
		type JsonInputFormat,
		type JsonStats,
	} from '$lib/services/formatters.js';
	import {
		CompareTab,
		ConvertTab,
		FormatTab,
		GenerateTab,
		QueryTab,
		SchemaTab,
	} from './tabs/index.js';

	// Valid tab types
	type TabType = 'format' | 'query' | 'compare' | 'convert' | 'schema' | 'generate';

	// Tab definitions
	const tabs = [
		{ value: 'format' as const, label: 'Format', icon: Play },
		{ value: 'query' as const, label: 'Query', icon: Search },
		{ value: 'compare' as const, label: 'Compare', icon: GitCompare },
		{ value: 'convert' as const, label: 'Convert', icon: ArrowRightLeft },
		{ value: 'schema' as const, label: 'Schema', icon: FileCheck },
		{ value: 'generate' as const, label: 'Generate', icon: CodeXml },
	] as const;

	// Extended stats type for JSON formatter
	interface JsonTabStats {
		input: string;
		valid: boolean | null;
		error: string;
		format: JsonInputFormat | null;
	}

	// Stats handler wrapper that includes format info
	let currentFormat = $state<JsonInputFormat | null>(null);

	const handleStatsChange =
		(handler: (stats: { input: string; valid: boolean | null; error: string }) => void) =>
		(stats: JsonTabStats) => {
			currentFormat = stats.format;
			handler({ input: stats.input, valid: stats.valid, error: stats.error });
		};
</script>

<svelte:head>
	<title>JSON Formatter - Kogu</title>
</svelte:head>

<FormatterPage
	title="JSON Formatter"
	{tabs}
	defaultTab="format"
	defaultInput=""
	calculateStats={calculateJsonStats}
>
	{#snippet formatBadge()}
		{#if currentFormat && currentFormat !== 'json'}
			<span class="rounded bg-primary/10 px-1.5 py-0.5 font-medium text-primary"
				>{JSON_FORMAT_INFO[currentFormat].label}</span
			>
		{/if}
	{/snippet}

	{#snippet statsSnippet(stats: JsonStats)}
		<span class="text-muted-foreground"
			>Keys: <strong class="text-foreground">{stats.keys}</strong></span
		>
		<span class="text-muted-foreground"
			>Values: <strong class="text-foreground">{stats.values}</strong></span
		>
		<span class="text-muted-foreground"
			>Depth: <strong class="text-foreground">{stats.depth}</strong></span
		>
		<span class="text-muted-foreground"
			>Size: <strong class="text-foreground">{stats.size}</strong></span
		>
	{/snippet}

	{#snippet tabContents(tab: TabType, sharedInput: string, setSharedInput: (value: string) => void, statsHandler: (stats: { input: string; valid: boolean | null; error: string }) => void)}
		{#if tab === 'format'}
			<FormatTab
				input={sharedInput}
				onInputChange={setSharedInput}
				onStatsChange={handleStatsChange(statsHandler)}
			/>
		{:else if tab === 'query'}
			<QueryTab
				input={sharedInput}
				onInputChange={setSharedInput}
				onStatsChange={handleStatsChange(statsHandler)}
			/>
		{:else if tab === 'compare'}
			<CompareTab
				input={sharedInput}
				onInputChange={setSharedInput}
				onStatsChange={handleStatsChange(statsHandler)}
			/>
		{:else if tab === 'convert'}
			<ConvertTab
				input={sharedInput}
				onInputChange={setSharedInput}
				onStatsChange={handleStatsChange(statsHandler)}
			/>
		{:else if tab === 'schema'}
			<SchemaTab
				input={sharedInput}
				onInputChange={setSharedInput}
				onStatsChange={handleStatsChange(statsHandler)}
			/>
		{:else if tab === 'generate'}
			<GenerateTab
				input={sharedInput}
				onInputChange={setSharedInput}
				onStatsChange={handleStatsChange(statsHandler)}
			/>
		{/if}
	{/snippet}
</FormatterPage>
