// src/routes/xml-formatter/tabs/format-tab.svelte
<script lang="ts">
	import { toast } from 'svelte-sonner';
	import type { ContextMenuItem } from '$lib/components/editor';
	import { CodeEditor } from '$lib/components/editor';
	import {
		FormCheckbox,
		FormCheckboxGroup,
		FormMode,
		FormSection,
		FormSelect,
	} from '$lib/components/form';
	import { SplitPane } from '$lib/components/layout';
	import { OptionsPanel } from '$lib/components/panel';
	import {
		defaultXmlFormatOptions,
		formatXml,
		minifyXml,
		SAMPLE_XML,
		type XmlFormatOptions,
	} from '$lib/services/formatters';

	interface Props {
		input: string;
		onInputChange: (value: string) => void;
		onStatsChange?: (stats: { input: string; valid: boolean | null; error: string }) => void;
	}

	let { input, onInputChange, onStatsChange }: Props = $props();

	// Mode and UI state
	let formatMode = $state<'format' | 'minify'>('format');
	let showOptions = $state(true);

	// Format options - Indentation
	let indentSizeStr = $state(String(defaultXmlFormatOptions.indentSize));
	let indentType = $state<'spaces' | 'tabs'>(defaultXmlFormatOptions.indentType);

	// Format options - Tags
	let whiteSpaceAtEndOfSelfclosingTag = $state(
		defaultXmlFormatOptions.whiteSpaceAtEndOfSelfclosingTag
	);
	let forceSelfClosingEmptyTag = $state(defaultXmlFormatOptions.forceSelfClosingEmptyTag);

	// Format options - Content
	let collapseContent = $state(defaultXmlFormatOptions.collapseContent);
	let preserveWhitespace = $state(defaultXmlFormatOptions.preserveWhitespace);
	let excludeComments = $state(defaultXmlFormatOptions.excludeComments);

	// Format options - Attributes
	let sortAttributes = $state(defaultXmlFormatOptions.sortAttributes);

	// Derived numeric values
	const indentSize = $derived(Number.parseInt(indentSizeStr, 10) || 2);

	// Format options object
	const formatOptions = $derived<Partial<XmlFormatOptions>>({
		indentSize,
		indentType,
		collapseContent,
		whiteSpaceAtEndOfSelfclosingTag,
		excludeComments,
		preserveWhitespace,
		forceSelfClosingEmptyTag,
		sortAttributes,
	});

	// Validation
	const validation = $derived.by(() => {
		if (!input.trim()) return { valid: null as boolean | null };
		try {
			const parser = new DOMParser();
			const doc = parser.parseFromString(input, 'application/xml');
			const parserError = doc.querySelector('parsererror');
			return { valid: parserError === null };
		} catch {
			return { valid: false };
		}
	});

	// Output calculation
	const formatResult = $derived.by((): { output: string; error: string } => {
		if (!input.trim()) return { output: '', error: '' };
		try {
			const output = formatMode === 'minify' ? minifyXml(input) : formatXml(input, formatOptions);
			return { output, error: '' };
		} catch (e) {
			return { output: '', error: e instanceof Error ? e.message : 'Invalid XML' };
		}
	});

	const output = $derived(formatResult.output);
	const formatError = $derived(formatResult.error);

	// Report stats to parent
	$effect(() => {
		onStatsChange?.({
			input,
			valid: validation.valid,
			error: formatError,
		});
	});

	// Handlers
	const handlePaste = async () => {
		try {
			const text = await navigator.clipboard.readText();
			if (text) onInputChange(text);
		} catch {
			// Clipboard access denied
		}
	};

	const handleClear = () => {
		onInputChange('');
	};

	const handleCopy = async () => {
		try {
			await navigator.clipboard.writeText(output);
			toast.success('Copied to clipboard');
		} catch {
			toast.error('Failed to copy to clipboard');
		}
	};

	const handleSample = () => {
		onInputChange(SAMPLE_XML);
	};

	// Format input XML
	const handleFormatInput = () => {
		try {
			const formatted = formatXml(input, { indentSize: 2, indentType: 'spaces' });
			onInputChange(formatted);
		} catch {
			// Invalid XML
		}
	};

	// Minify input XML
	const handleMinifyInput = () => {
		try {
			const minified = minifyXml(input);
			onInputChange(minified);
		} catch {
			// Invalid XML
		}
	};

	// Context menu items for input editor
	const inputContextMenuItems = $derived<ContextMenuItem[]>([
		{
			text: 'Format XML',
			enabled: !!input.trim(),
			action: handleFormatInput,
		},
		{
			text: 'Minify XML',
			enabled: !!input.trim(),
			action: handleMinifyInput,
		},
	]);
</script>

<div class="flex flex-1 overflow-hidden">
	<OptionsPanel
		show={showOptions}
		onclose={() => (showOptions = false)}
		onopen={() => (showOptions = true)}
	>
		<FormSection title="Mode">
			<FormMode
				bind:value={formatMode}
				options={[
					{ value: 'format', label: 'Format' },
					{ value: 'minify', label: 'Minify' },
				]}
			/>
		</FormSection>

		<FormSection title="Indentation">
			<div class="grid grid-cols-2 gap-2">
				<FormSelect label="Size" bind:value={indentSizeStr} options={['1', '2', '4', '8']} />
				<FormSelect
					label="Type"
					bind:value={indentType}
					options={[
						{ value: 'spaces', label: 'Spaces' },
						{ value: 'tabs', label: 'Tabs' },
					]}
				/>
			</div>
		</FormSection>

		<FormSection title="Tags">
			<FormCheckbox
				label="Space before self-closing />"
				bind:checked={whiteSpaceAtEndOfSelfclosingTag}
			/>
			<FormCheckbox label="Force self-closing empty tags" bind:checked={forceSelfClosingEmptyTag} />
		</FormSection>

		<FormSection title="Content">
			<FormCheckboxGroup>
				<FormCheckbox label="Collapse content on single line" bind:checked={collapseContent} />
				<FormCheckbox label="Preserve whitespace" bind:checked={preserveWhitespace} />
				<FormCheckbox label="Remove comments" bind:checked={excludeComments} />
			</FormCheckboxGroup>
		</FormSection>

		<FormSection title="Attributes">
			<FormCheckbox label="Sort attributes alphabetically" bind:checked={sortAttributes} />
		</FormSection>
	</OptionsPanel>

	<SplitPane class="h-full flex-1">
		{#snippet left()}
			<CodeEditor
				title="Input"
				value={input}
				onchange={onInputChange}
				mode="input"
				editorMode="xml"
				placeholder="Enter XML here..."
				onsample={handleSample}
				onpaste={handlePaste}
				onclear={handleClear}
				contextMenuItems={inputContextMenuItems}
			/>
		{/snippet}
		{#snippet right()}
			<CodeEditor
				title="Output"
				value={output}
				mode="readonly"
				editorMode="xml"
				placeholder="Formatted output..."
				oncopy={handleCopy}
			/>
		{/snippet}
	</SplitPane>
</div>

// src/lib/components/formatter-tabs/xml/format-tab.tsx
import { FileText } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { toast } from 'sonner';

import { CodeEditor, type ContextMenuItem } from '@/lib/components/editor';
import {
	FormCheckbox,
	FormCheckboxGroup,
	FormMode,
	FormSection,
	FormSelect,
} from '@/lib/components/form';
import { SplitPane } from '@/lib/components/layout';
import { OptionsPanel } from '@/lib/components/panel';
import { EmptyOutputPane } from '@/lib/components/status';
import {
	defaultXmlFormatOptions,
	formatXml,
	minifyXml,
	SAMPLE_XML,
	type XmlFormatOptions,
} from '@/lib/services/formatters';

type FormatMode = 'format' | 'minify';
type IndentType = 'spaces' | 'tabs';

interface TabStats {
	readonly input: string;
	readonly valid: boolean | null;
	readonly error: string;
}

interface FormatTabProps {
	readonly input: string;
	readonly onInputChange: (value: string) => void;
	readonly onStatsChange?: (stats: TabStats) => void;
}

export function FormatTab({ input, onInputChange, onStatsChange }: FormatTabProps) {
	const [formatMode, setFormatMode] = useState<FormatMode>('format');
	const [showOptions, setShowOptions] = useState(true);

	// Indentation options.
	const [indentSizeStr, setIndentSizeStr] = useState<string>(
		String(defaultXmlFormatOptions.indentSize)
	);
	const [indentType, setIndentType] = useState<IndentType>(defaultXmlFormatOptions.indentType);

	// Tag options.
	const [whiteSpaceAtEndOfSelfclosingTag, setWhiteSpaceAtEndOfSelfclosingTag] = useState<boolean>(
		defaultXmlFormatOptions.whiteSpaceAtEndOfSelfclosingTag
	);
	const [forceSelfClosingEmptyTag, setForceSelfClosingEmptyTag] = useState<boolean>(
		defaultXmlFormatOptions.forceSelfClosingEmptyTag
	);

	// Content options.
	const [collapseContent, setCollapseContent] = useState<boolean>(
		defaultXmlFormatOptions.collapseContent
	);
	const [preserveWhitespace, setPreserveWhitespace] = useState<boolean>(
		defaultXmlFormatOptions.preserveWhitespace
	);
	const [excludeComments, setExcludeComments] = useState<boolean>(
		defaultXmlFormatOptions.excludeComments
	);

	// Attribute options.
	const [sortAttributes, setSortAttributes] = useState<boolean>(
		defaultXmlFormatOptions.sortAttributes
	);

	const indentSize = Number.parseInt(indentSizeStr, 10) || 2;

	const formatOptions: Partial<XmlFormatOptions> = {
		indentSize,
		indentType,
		collapseContent,
		whiteSpaceAtEndOfSelfclosingTag,
		excludeComments,
		preserveWhitespace,
		forceSelfClosingEmptyTag,
		sortAttributes,
	};

	const validation = useMemo<{ valid: boolean | null }>(() => {
		if (!input.trim()) return { valid: null };
		try {
			const parser = new DOMParser();
			const doc = parser.parseFromString(input, 'application/xml');
			const parserError = doc.querySelector('parsererror');
			return { valid: parserError === null };
		} catch {
			return { valid: false };
		}
	}, [input]);

	const { output, error: formatError } = ((): { output: string; error: string } => {
		if (!input.trim()) return { output: '', error: '' };
		try {
			const result = formatMode === 'minify' ? minifyXml(input) : formatXml(input, formatOptions);
			return { output: result, error: '' };
		} catch (e) {
			return { output: '', error: e instanceof Error ? e.message : 'Invalid XML' };
		}
	})();

	// Report stats to parent.
	useEffect(() => {
		onStatsChange?.({
			input,
			valid: validation.valid,
			error: formatError,
		});
	}, [input, validation.valid, formatError, onStatsChange]);

	const handlePaste = async () => {
		try {
			const text = await navigator.clipboard.readText();
			if (text) onInputChange(text);
		} catch {
			// Clipboard access denied.
		}
	};

	const handleClear = () => {
		onInputChange('');
	};

	const handleCopy = async () => {
		try {
			await navigator.clipboard.writeText(output);
			toast.success('Copied to clipboard');
		} catch {
			toast.error('Failed to copy to clipboard');
		}
	};

	const handleSample = () => {
		onInputChange(SAMPLE_XML);
	};

	const handleFormatInput = () => {
		try {
			const formatted = formatXml(input, { indentSize: 2, indentType: 'spaces' });
			onInputChange(formatted);
		} catch {
			// Invalid XML.
		}
	};

	const handleMinifyInput = () => {
		try {
			const minified = minifyXml(input);
			onInputChange(minified);
		} catch {
			// Invalid XML.
		}
	};

	const inputContextMenuItems: readonly ContextMenuItem[] = [
		{
			text: 'Format XML',
			enabled: input.trim().length > 0,
			action: handleFormatInput,
		},
		{
			text: 'Minify XML',
			enabled: input.trim().length > 0,
			action: handleMinifyInput,
		},
	];

	return (
		<div className="flex flex-1 overflow-hidden">
			<OptionsPanel
				show={showOptions}
				onClose={() => setShowOptions(false)}
				onOpen={() => setShowOptions(true)}
			>
				<FormSection title="Mode">
					<FormMode
						value={formatMode}
						onValueChange={setFormatMode}
						options={[
							{ value: 'format', label: 'Format' },
							{ value: 'minify', label: 'Minify' },
						]}
					/>
				</FormSection>

				<FormSection title="Indentation">
					<div className="grid grid-cols-2 gap-2">
						<FormSelect
							label="Size"
							value={indentSizeStr}
							onValueChange={setIndentSizeStr}
							options={['1', '2', '4', '8']}
							size="compact"
						/>
						<FormSelect
							label="Type"
							value={indentType}
							onValueChange={(v) => setIndentType(v as IndentType)}
							options={[
								{ value: 'spaces', label: 'Spaces' },
								{ value: 'tabs', label: 'Tabs' },
							]}
							size="compact"
						/>
					</div>
				</FormSection>

				<FormSection title="Tags">
					<FormCheckbox
						label="Space before self-closing />"
						checked={whiteSpaceAtEndOfSelfclosingTag}
						onCheckedChange={setWhiteSpaceAtEndOfSelfclosingTag}
						size="compact"
					/>
					<FormCheckbox
						label="Force self-closing empty tags"
						checked={forceSelfClosingEmptyTag}
						onCheckedChange={setForceSelfClosingEmptyTag}
						size="compact"
					/>
				</FormSection>

				<FormSection title="Content">
					<FormCheckboxGroup>
						<FormCheckbox
							label="Collapse content on single line"
							checked={collapseContent}
							onCheckedChange={setCollapseContent}
							size="compact"
						/>
						<FormCheckbox
							label="Preserve whitespace"
							checked={preserveWhitespace}
							onCheckedChange={setPreserveWhitespace}
							size="compact"
						/>
						<FormCheckbox
							label="Remove comments"
							checked={excludeComments}
							onCheckedChange={setExcludeComments}
							size="compact"
						/>
					</FormCheckboxGroup>
				</FormSection>

				<FormSection title="Attributes">
					<FormCheckbox
						label="Sort attributes alphabetically"
						checked={sortAttributes}
						onCheckedChange={setSortAttributes}
						size="compact"
					/>
				</FormSection>
			</OptionsPanel>

			<SplitPane
				className="h-full flex-1"
				left={
					<CodeEditor
						title="Input"
						value={input}
						onChange={onInputChange}
						mode="input"
						editorMode="xml"
						placeholder="Enter XML here..."
						onSample={handleSample}
						onPaste={handlePaste}
						onClear={handleClear}
						contextMenuItems={inputContextMenuItems}
					/>
				}
				right={
					input.trim().length === 0 ? (
						<EmptyOutputPane
							headerTitle="Output"
							icon={FileText}
							title="Enter XML to format"
							description="The formatted (or minified) document will appear here."
						/>
					) : (
						<CodeEditor
							title="Output"
							value={output}
							mode="readonly"
							editorMode="xml"
							placeholder="Formatted output..."
							onCopy={handleCopy}
						/>
					)
				}
			/>
		</div>
	);
}

export type { FormatTabProps };
