// src/lib/components/shell/tool-bar.tsx
import type { ReactNode } from 'react';
import { useRouterState } from '@tanstack/react-router';

import { getPageByUrl } from '@/lib/services/pages';

interface ToolBarProps {
	readonly title?: string;
	readonly leading?: ReactNode;
	readonly center?: ReactNode;
	readonly trailing?: ReactNode;
}

export function ToolBar({ title: titleOverride, leading, center, trailing }: ToolBarProps) {
	const pathname = useRouterState({ select: (state) => state.location.pathname });
	const pageDefinition = getPageByUrl(pathname);
	const title = titleOverride ?? pageDefinition?.title ?? 'Untitled';
	const PageIcon = pageDefinition?.icon;

	return (
		<header className="grid h-12 shrink-0 grid-cols-[auto_1fr_auto] items-center border-b bg-surface-1 px-4">
			<div className="flex min-w-0 shrink-0 items-center gap-2">
				{PageIcon ? <PageIcon className="h-4 w-4 shrink-0 opacity-80" /> : null}
				<h1 className="truncate text-sm font-bold tracking-tight">{title}</h1>
				{leading}
			</div>

			<div className="flex min-w-0 items-center justify-center">{center}</div>

			<div className="flex shrink-0 items-center justify-end gap-1">{trailing}</div>
		</header>
	);
}

export type { ToolBarProps };

// src/lib/components/shell/tool-bar.svelte
<script lang="ts">
	import type { Component, Snippet } from 'svelte';
	import { page } from '$app/state';
	import { getPageByUrl } from '$lib/services/pages.js';

	interface Props {
		readonly title?: string;
		readonly leading?: Snippet;
		readonly center?: Snippet;
		readonly trailing?: Snippet;
	}

	let { title: titleOverride, leading, center, trailing }: Props = $props();

	const pageDefinition = $derived(getPageByUrl(page.url.pathname));
	const title = $derived(titleOverride ?? pageDefinition?.title ?? 'Untitled');
	const PageIcon: Component | undefined = $derived(pageDefinition?.icon);
</script>

<header
	class="grid h-12 shrink-0 grid-cols-[auto_1fr_auto] items-center border-b bg-surface-1 px-4"
>
	<!-- Left: Always icon + title -->
	<div class="flex min-w-0 shrink-0 items-center gap-2">
		{#if PageIcon}
			<PageIcon class="h-4 w-4 shrink-0 opacity-80" />
		{/if}
		<h1 class="truncate text-sm font-bold tracking-tight">{title}</h1>
		{#if leading}
			{@render leading()}
		{/if}
	</div>

	<!-- Center: tabs or custom -->
	<div class="flex min-w-0 items-center justify-center">
		{#if center}
			{@render center()}
		{/if}
	</div>

	<!-- Right: trailing actions -->
	<div class="flex shrink-0 items-center justify-end gap-1">
		{#if trailing}
			{@render trailing()}
		{/if}
	</div>
</header>
