// src/lib/components/shell/tool-shell.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import * as Tabs from '$lib/components/ui/tabs/index.js';
	import ToolBar from './tool-bar.svelte';
	import OptionsRail from './options-rail.svelte';
	import StatusBar from './status-bar.svelte';
	import { isModKey } from '$lib/utils/keyboard.js';

	interface TabDefinition {
		readonly id: string;
		readonly label: string;
		readonly icon: import('svelte').Component;
	}

	interface Props {
		readonly layout?: 'tabbed' | 'transform' | 'master-detail';

		// Toolbar
		readonly title?: string;
		readonly toolbarLeading?: Snippet;
		readonly toolbarCenter?: Snippet;
		readonly toolbarTrailing?: Snippet;

		// Tabs (integrated toolbar tabs). All tab panels remain mounted thanks to
		// the bits-ui Tabs.Content default behavior (inactive panels are hidden via
		// the `hidden` attribute, not unmounted), so component state is preserved
		// across tab switches without an explicit opt-in.
		readonly tabs?: readonly TabDefinition[];
		readonly activeTab?: string;
		readonly ontabchange?: (tab: string) => void;
		readonly tabContent?: Snippet<[string]>;

		// Options rail
		showRail?: boolean;
		readonly railTitle?: string;
		readonly rail?: Snippet;

		// Status bar
		readonly valid?: boolean | null;
		readonly error?: string;
		readonly statusContent?: Snippet;

		// Main content
		readonly children?: Snippet;
	}

	let {
		layout = 'transform',
		title,
		toolbarLeading,
		toolbarCenter,
		toolbarTrailing,
		tabs,
		activeTab,
		ontabchange,
		tabContent,
		showRail = $bindable(true),
		railTitle = 'Options',
		rail,
		valid,
		error,
		statusContent,
		children,
	}: Props = $props();

	let shellRef = $state<HTMLElement | null>(null);

	const hasTabs = $derived(!!tabs && tabs.length > 0);

	const railState = $derived.by(() => {
		if (!rail) return 'none';
		return showRail ? 'open' : 'closed';
	});

	const handleShellKeydown = (e: KeyboardEvent) => {
		if (!isModKey(e)) return;
		// Skip while the user is composing in an IME so Cmd+1..9 cannot hijack
		// candidate selection.
		if (e.isComposing) return;

		// Cmd+, → toggle options rail
		if (e.key === ',' && rail) {
			e.preventDefault();
			showRail = !showRail;
			return;
		}

		// Cmd+1-9 → switch tabs
		if (e.key >= '1' && e.key <= '9' && tabs && tabs.length > 0) {
			const idx = Number.parseInt(e.key, 10) - 1;
			const tab = tabs[idx];
			if (tab) {
				e.preventDefault();
				ontabchange?.(tab.id);
			}
		}
	};

	const handleValueChange = (value: string) => {
		ontabchange?.(value);
	};

	// Scope the keyboard listener to the shell container so it only fires when
	// focus is inside the tool, not on unrelated parts of the page.
	$effect(() => {
		const el = shellRef;
		if (!el) return;
		el.addEventListener('keydown', handleShellKeydown);
		return () => el.removeEventListener('keydown', handleShellKeydown);
	});
</script>

{#snippet shell()}
	<div class="tool-shell" bind:this={shellRef} data-layout={layout} data-rail={railState}>
		<!-- Toolbar -->
		<div class="tool-toolbar">
			<ToolBar {title}>
				{#snippet leading()}
					{#if toolbarLeading}
						{@render toolbarLeading()}
					{/if}
				{/snippet}

				{#snippet center()}
					{#if toolbarCenter}
						{@render toolbarCenter()}
					{:else if hasTabs && tabs}
						<Tabs.List
							class="bg-surface-2 inline-flex h-auto items-center gap-0.5 rounded-lg p-1 shadow-inner"
						>
							{#each tabs as tab (tab.id)}
								{@const TabIcon = tab.icon}
								<Tabs.Trigger
									value={tab.id}
									class="data-[state=active]:bg-surface-0 data-[state=active]:text-foreground data-[state=active]:shadow-sm text-muted-foreground hover:bg-interactive-hover hover:text-foreground inline-flex flex-none items-center gap-1.5 rounded-md border-0 px-3.5 py-2 text-sm font-medium transition-all duration-base"
								>
									<TabIcon class="h-4 w-4" />
									{tab.label}
								</Tabs.Trigger>
							{/each}
						</Tabs.List>
					{/if}
				{/snippet}

				{#snippet trailing()}
					{#if toolbarTrailing}
						{@render toolbarTrailing()}
					{/if}
				{/snippet}
			</ToolBar>
		</div>

		<!-- Options Rail -->
		{#if rail}
			<div class="tool-rail">
				<OptionsRail
					bind:show={showRail}
					title={railTitle}
					onclose={() => (showRail = false)}
					onopen={() => (showRail = true)}
				>
					{@render rail()}
				</OptionsRail>
			</div>
		{/if}

		<!-- Main Content -->
		<div class="tool-content animate-fade-in">
			{#if hasTabs && tabContent && tabs && activeTab}
				{#each tabs as tab (tab.id)}
					<Tabs.Content
						value={tab.id}
						class="flex h-full min-h-0 flex-1 flex-col data-[state=inactive]:hidden"
					>
						{@render tabContent(tab.id)}
					</Tabs.Content>
				{/each}
			{:else if children}
				{@render children()}
			{/if}
		</div>

		<!-- Status Bar -->
		<div class="tool-status">
			<StatusBar {valid} {error}>
				{#if statusContent}
					{@render statusContent()}
				{/if}
			</StatusBar>
		</div>
	</div>
{/snippet}

{#if hasTabs && tabs && activeTab}
	<Tabs.Root value={activeTab} onValueChange={handleValueChange} class="contents">
		{@render shell()}
	</Tabs.Root>
{:else}
	{@render shell()}
{/if}

<style>
	.tool-shell {
		display: grid;
		height: 100%;
		overflow: hidden;
		grid-template-rows: var(--toolbar-h) 1fr var(--status-h);
	}

	/* Rail open */
	.tool-shell[data-rail='open'] {
		grid-template-columns: var(--rail-w) 1fr;
		grid-template-areas:
			'toolbar toolbar'
			'rail content'
			'status status';
	}

	/* Rail collapsed */
	.tool-shell[data-rail='closed'] {
		grid-template-columns: var(--rail-w-collapsed) 1fr;
		grid-template-areas:
			'toolbar toolbar'
			'rail content'
			'status status';
	}

	/* No rail */
	.tool-shell[data-rail='none'] {
		grid-template-columns: 1fr;
		grid-template-areas:
			'toolbar'
			'content'
			'status';
	}

	.tool-toolbar {
		grid-area: toolbar;
	}

	.tool-rail {
		grid-area: rail;
		overflow: hidden;
		display: flex;
		flex-direction: column;
	}

	.tool-content {
		grid-area: content;
		overflow: hidden;
		display: flex;
		flex-direction: column;
	}

	.tool-status {
		grid-area: status;
	}
</style>

// src/lib/components/shell/tool-shell.tsx
import { useCallback, useEffect, useMemo, useRef, useState, type ReactNode } from 'react';
import type { LucideIcon } from 'lucide-react';

import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/lib/components/ui/tabs';
import { isModKey } from '@/lib/utils/keyboard';

import { OptionsRail } from './options-rail';
import { StatusBar } from './status-bar';
import { ToolBar } from './tool-bar';

interface TabDefinition {
	readonly id: string;
	readonly label: string;
	readonly icon: LucideIcon;
}

type ShellLayout = 'tabbed' | 'transform' | 'master-detail';

interface ToolShellProps {
	readonly layout?: ShellLayout;

	readonly title?: string;
	readonly toolbarLeading?: ReactNode;
	readonly toolbarCenter?: ReactNode;
	readonly toolbarTrailing?: ReactNode;

	readonly tabs?: readonly TabDefinition[];
	readonly activeTab?: string;
	readonly onTabChange?: (tab: string) => void;
	readonly renderTabContent?: (tabId: string) => ReactNode;

	readonly showRail?: boolean;
	readonly defaultShowRail?: boolean;
	readonly onShowRailChange?: (show: boolean) => void;
	readonly railTitle?: string;
	readonly rail?: ReactNode;

	readonly valid?: boolean | null;
	readonly error?: string;
	readonly statusContent?: ReactNode;

	readonly children?: ReactNode;
}

export function ToolShell({
	layout = 'transform',
	title,
	toolbarLeading,
	toolbarCenter,
	toolbarTrailing,
	tabs,
	activeTab,
	onTabChange,
	renderTabContent,
	showRail: controlledShowRail,
	defaultShowRail = true,
	onShowRailChange,
	railTitle = 'Options',
	rail,
	valid,
	error,
	statusContent,
	children,
}: ToolShellProps) {
	const [internalShowRail, setInternalShowRail] = useState(defaultShowRail);
	const showRail = controlledShowRail ?? internalShowRail;

	const setShowRail = useCallback(
		(next: boolean) => {
			if (controlledShowRail === undefined) setInternalShowRail(next);
			onShowRailChange?.(next);
		},
		[controlledShowRail, onShowRailChange]
	);

	const shellRef = useRef<HTMLDivElement | null>(null);
	const hasTabs = Boolean(tabs && tabs.length > 0);

	const railState = useMemo<'open' | 'closed' | 'none'>(() => {
		if (!rail) return 'none';
		return showRail ? 'open' : 'closed';
	}, [rail, showRail]);

	useEffect(() => {
		const el = shellRef.current;
		if (!el) return;
		const handler = (e: KeyboardEvent) => {
			if (!isModKey(e)) return;
			// Skip while the user is composing in an IME so Cmd+1..9 cannot hijack
			// candidate selection.
			if (e.isComposing) return;

			if (e.key === ',' && rail) {
				e.preventDefault();
				setShowRail(!showRail);
				return;
			}

			if (e.key >= '1' && e.key <= '9' && tabs && tabs.length > 0) {
				const idx = Number.parseInt(e.key, 10) - 1;
				const tab = tabs[idx];
				if (tab) {
					e.preventDefault();
					onTabChange?.(tab.id);
				}
			}
		};
		el.addEventListener('keydown', handler);
		return () => el.removeEventListener('keydown', handler);
	}, [rail, showRail, setShowRail, tabs, onTabChange]);

	const shell = (
		<div ref={shellRef} className="tool-shell" data-layout={layout} data-rail={railState}>
			<div className="tool-toolbar">
				<ToolBar
					title={title}
					leading={toolbarLeading}
					trailing={toolbarTrailing}
					center={
						toolbarCenter ??
						(hasTabs && tabs ? (
							<TabsList className="inline-flex h-auto items-center gap-0.5 rounded-lg bg-surface-2 p-1 shadow-inner">
								{tabs.map((tab) => {
									const TabIcon = tab.icon;
									return (
										<TabsTrigger
											key={tab.id}
											value={tab.id}
											className="inline-flex flex-none items-center gap-1.5 rounded-md border-0 px-3.5 py-2 text-sm font-medium text-muted-foreground transition-all duration-base hover:bg-interactive-hover hover:text-foreground data-active:bg-surface-0 data-active:text-foreground data-active:shadow-sm"
										>
											<TabIcon className="h-4 w-4" />
											{tab.label}
										</TabsTrigger>
									);
								})}
							</TabsList>
						) : null)
					}
				/>
			</div>

			{rail ? (
				<div className="tool-rail">
					<OptionsRail
						show={showRail}
						title={railTitle}
						onShowChange={setShowRail}
						onClose={() => setShowRail(false)}
						onOpen={() => setShowRail(true)}
					>
						{rail}
					</OptionsRail>
				</div>
			) : null}

			<div className="tool-content animate-fade-in">
				{hasTabs && renderTabContent && tabs && activeTab
					? tabs.map((tab) => (
							<TabsContent
								key={tab.id}
								value={tab.id}
								className="flex h-full min-h-0 flex-1 flex-col data-[state=inactive]:hidden"
							>
								{renderTabContent(tab.id)}
							</TabsContent>
						))
					: children}
			</div>

			<div className="tool-status">
				<StatusBar valid={valid} error={error}>
					{statusContent}
				</StatusBar>
			</div>

			<style>{`
				.tool-shell {
					display: grid;
					height: 100%;
					overflow: hidden;
					grid-template-rows: var(--toolbar-h) 1fr var(--status-h);
				}
				.tool-shell[data-rail='open'] {
					grid-template-columns: var(--rail-w) 1fr;
					grid-template-areas:
						'toolbar toolbar'
						'rail content'
						'status status';
				}
				.tool-shell[data-rail='closed'] {
					grid-template-columns: var(--rail-w-collapsed) 1fr;
					grid-template-areas:
						'toolbar toolbar'
						'rail content'
						'status status';
				}
				.tool-shell[data-rail='none'] {
					grid-template-columns: 1fr;
					grid-template-areas:
						'toolbar'
						'content'
						'status';
				}
				.tool-toolbar { grid-area: toolbar; }
				.tool-rail { grid-area: rail; overflow: hidden; display: flex; flex-direction: column; }
				.tool-content { grid-area: content; overflow: hidden; display: flex; flex-direction: column; }
				.tool-status { grid-area: status; }
			`}</style>
		</div>
	);

	if (hasTabs && tabs && activeTab) {
		return (
			<Tabs value={activeTab} onValueChange={onTabChange} className="contents">
				{shell}
			</Tabs>
		);
	}

	return shell;
}

export type { ToolShellProps, TabDefinition, ShellLayout };
