// src/lib/components/layout/app-sidebar.tsx
import { useState } from 'react';
import { Link, useRouterState } from '@tanstack/react-router';
import { useTheme } from 'next-themes';
import { ChevronLeft, ChevronRight, Monitor, Moon, Settings, Sun } from 'lucide-react';

import {
	Collapsible,
	CollapsibleContent,
	CollapsibleTrigger,
} from '@/lib/components/ui/collapsible';
import {
	Sidebar,
	SidebarContent,
	SidebarFooter,
	SidebarGroup,
	SidebarGroupContent,
	SidebarGroupLabel,
	SidebarHeader,
	SidebarMenu,
	SidebarMenuButton,
	SidebarMenuItem,
	SidebarRail,
	useSidebar,
} from '@/lib/components/ui/sidebar';
import { CATEGORIES, getPagesByCategory } from '@/lib/services/pages';
import { cn } from '@/lib/utils';

type ThemeName = 'light' | 'dark' | 'system';

const cycleTheme = (current: ThemeName): ThemeName => {
	if (current === 'light') return 'dark';
	if (current === 'dark') return 'system';
	return 'light';
};

const isThemeName = (value: string | undefined): value is ThemeName =>
	value === 'light' || value === 'dark' || value === 'system';

export function AppSidebar(_: AppSidebarProps = {}) {
	// TODO(Phase 4): wire to Zustand persisted store
	const [openGroups, setOpenGroups] = useState<Record<string, boolean>>(() =>
		Object.fromEntries(CATEGORIES.map((c) => [c.id, c.defaultOpen]))
	);

	const pathname = useRouterState({ select: (state) => state.location.pathname });
	const sidebar = useSidebar();
	const { theme, setTheme } = useTheme();
	const activeTheme: ThemeName = isThemeName(theme) ? theme : 'system';

	const handleToggleTheme = () => {
		setTheme(cycleTheme(activeTheme));
	};

	return (
		<Sidebar collapsible="icon">
			<SidebarHeader className="border-b border-sidebar-border/50 pb-2">
				<SidebarMenu>
					<SidebarMenuItem>
						<SidebarMenuButton
							size="lg"
							className="data-open:bg-sidebar-accent data-open:text-sidebar-accent-foreground"
							asChild
						>
							<Link to="/">
								<img src="/logo.svg" alt="Kogu" className="size-8 rounded-lg" />
								<div className="grid flex-1 text-left text-sm leading-tight">
									<span className="truncate font-semibold">Kogu</span>
									<span className="truncate text-xs text-muted-foreground">Developer Tools</span>
								</div>
							</Link>
						</SidebarMenuButton>
					</SidebarMenuItem>
				</SidebarMenu>
			</SidebarHeader>

			<SidebarContent>
				{CATEGORIES.map((category) => {
					const CategoryIcon = category.icon;
					const categoryPages = getPagesByCategory(category.id);
					const isOpen = openGroups[category.id] ?? false;
					return (
						<Collapsible
							key={category.id}
							open={isOpen}
							onOpenChange={(open) => setOpenGroups((prev) => ({ ...prev, [category.id]: open }))}
							className="group/collapsible"
						>
							<SidebarGroup>
								<SidebarGroupLabel className="group/label p-0 text-sidebar-foreground hover:bg-sidebar-accent hover:text-sidebar-accent-foreground">
									<CollapsibleTrigger
										className={cn(
											'flex w-full items-center gap-2 border-l-2 px-2 py-1.5',
											category.borderClass
										)}
									>
										<CategoryIcon className="size-4 opacity-70" />
										<span className="flex-1 text-left text-xs font-semibold uppercase tracking-wider">
											{category.label}
										</span>
										<ChevronRight className="size-4 transition-transform duration-200 group-data-[state=open]/collapsible:rotate-90" />
									</CollapsibleTrigger>
								</SidebarGroupLabel>
								<CollapsibleContent>
									<SidebarGroupContent>
										<SidebarMenu>
											{categoryPages.map((tool) => {
												const ToolIcon = tool.icon;
												return (
													<SidebarMenuItem key={tool.id}>
														<SidebarMenuButton
															isActive={pathname === tool.url}
															tooltip={tool.title}
															asChild
														>
															<Link to={tool.url as never}>
																<ToolIcon />
																<span>{tool.title}</span>
															</Link>
														</SidebarMenuButton>
													</SidebarMenuItem>
												);
											})}
										</SidebarMenu>
									</SidebarGroupContent>
								</CollapsibleContent>
							</SidebarGroup>
						</Collapsible>
					);
				})}
			</SidebarContent>

			<SidebarFooter className="border-t border-sidebar-border py-1.5">
				<SidebarMenu>
					<SidebarMenuItem>
						<SidebarMenuButton isActive={pathname === '/settings'} tooltip="Settings" asChild>
							<Link to="/settings">
								<Settings className="size-4" />
								<span>Settings</span>
							</Link>
						</SidebarMenuButton>
					</SidebarMenuItem>
					<SidebarMenuItem>
						<SidebarMenuButton onClick={handleToggleTheme} tooltip="Toggle theme">
							{activeTheme === 'dark' ? (
								<>
									<Moon className="size-4" />
									<span>Dark Mode</span>
								</>
							) : activeTheme === 'light' ? (
								<>
									<Sun className="size-4" />
									<span>Light Mode</span>
								</>
							) : (
								<>
									<Monitor className="size-4" />
									<span>System</span>
								</>
							)}
						</SidebarMenuButton>
					</SidebarMenuItem>
					<SidebarMenuItem>
						<SidebarMenuButton onClick={sidebar.toggleSidebar} tooltip="Toggle sidebar">
							<ChevronLeft className="size-4 transition-transform duration-200 group-data-[state=collapsed]:rotate-180" />
							<span>Collapse</span>
						</SidebarMenuButton>
					</SidebarMenuItem>
				</SidebarMenu>
			</SidebarFooter>

			<SidebarRail />
		</Sidebar>
	);
}

export type AppSidebarProps = {
	readonly className?: string;
};

// src/lib/components/layout/app-sidebar.svelte
<script lang="ts">
	import { ChevronLeft, ChevronRight, Monitor, Moon, Settings, Sun } from '@lucide/svelte';
	import { mode, toggleMode } from 'mode-watcher';
	import { page } from '$app/state';
	import * as Collapsible from '$lib/components/ui/collapsible/index.js';
	import * as Sidebar from '$lib/components/ui/sidebar/index.js';
	import { CATEGORIES, getPagesByCategory } from '$lib/services/pages.js';

	// Track open state for each collapsible group
	let openGroups = $state<Record<string, boolean>>(
		Object.fromEntries(CATEGORIES.map((c) => [c.id, c.defaultOpen]))
	);

	const sidebar = Sidebar.useSidebar();
</script>

<Sidebar.Root collapsible="icon">
	<!-- Header with Logo -->
	<Sidebar.Header class="border-b border-sidebar-border/50 pb-2">
		<Sidebar.Menu>
			<Sidebar.MenuItem>
				<Sidebar.MenuButton
					size="lg"
					class="data-[state=open]:bg-sidebar-accent data-[state=open]:text-sidebar-accent-foreground"
				>
					{#snippet child({ props })}
						<a href="/" {...props}>
							<img src="/logo.svg" alt="Kogu" class="size-8 rounded-lg" />
							<div class="grid flex-1 text-left text-sm leading-tight">
								<span class="truncate font-semibold">Kogu</span>
								<span class="truncate text-xs text-muted-foreground">Developer Tools</span>
							</div>
						</a>
					{/snippet}
				</Sidebar.MenuButton>
			</Sidebar.MenuItem>
		</Sidebar.Menu>
	</Sidebar.Header>

	<!-- Main Navigation -->
	<Sidebar.Content>
		<!-- Category Groups -->
		{#each CATEGORIES as category}
			{@const CategoryIcon = category.icon}
			{@const categoryPages = getPagesByCategory(category.id)}
			<Collapsible.Root bind:open={openGroups[category.id]} class="group/collapsible">
				<Sidebar.Group>
					<Sidebar.GroupLabel
						class="group/label text-sidebar-foreground hover:bg-sidebar-accent hover:text-sidebar-accent-foreground p-0"
					>
						<Collapsible.Trigger
							class="flex w-full items-center gap-2 border-l-2 {category.borderClass} px-2 py-1.5"
						>
							<CategoryIcon class="size-4 opacity-70" />
							<span class="flex-1 text-left text-xs font-semibold uppercase tracking-wider"
								>{category.label}</span
							>
							<ChevronRight
								class="size-4 transition-transform duration-200 group-data-[state=open]/collapsible:rotate-90"
							/>
						</Collapsible.Trigger>
					</Sidebar.GroupLabel>
					<Collapsible.Content>
						<Sidebar.GroupContent>
							<Sidebar.Menu>
								{#each categoryPages as tool}
									<Sidebar.MenuItem>
										<Sidebar.MenuButton
											isActive={page.url.pathname === tool.url}
											tooltipContent={tool.title}
										>
											{#snippet child({ props })}
												<a href={tool.url} {...props}>
													<tool.icon />
													<span>{tool.title}</span>
												</a>
											{/snippet}
										</Sidebar.MenuButton>
									</Sidebar.MenuItem>
								{/each}
							</Sidebar.Menu>
						</Sidebar.GroupContent>
					</Collapsible.Content>
				</Sidebar.Group>
			</Collapsible.Root>
		{/each}
	</Sidebar.Content>

	<!-- Footer with Settings, Theme Toggle and Collapse Button -->
	<Sidebar.Footer class="border-t border-sidebar-border py-1.5">
		<Sidebar.Menu>
			<Sidebar.MenuItem>
				<Sidebar.MenuButton isActive={page.url.pathname === '/settings'} tooltipContent="Settings">
					{#snippet child({ props })}
						<a href="/settings" {...props}>
							<Settings class="size-4" />
							<span>Settings</span>
						</a>
					{/snippet}
				</Sidebar.MenuButton>
			</Sidebar.MenuItem>
			<Sidebar.MenuItem>
				<Sidebar.MenuButton onclick={toggleMode} tooltipContent="Toggle theme">
					{#if mode.current === 'dark'}
						<Moon class="size-4" />
						<span>Dark Mode</span>
					{:else if mode.current === 'light'}
						<Sun class="size-4" />
						<span>Light Mode</span>
					{:else}
						<Monitor class="size-4" />
						<span>System</span>
					{/if}
				</Sidebar.MenuButton>
			</Sidebar.MenuItem>
			<Sidebar.MenuItem>
				<Sidebar.MenuButton onclick={sidebar.toggle} tooltipContent="Toggle sidebar">
					<ChevronLeft
						class="size-4 transition-transform duration-200 group-data-[state=collapsed]:rotate-180"
					/>
					<span>Collapse</span>
				</Sidebar.MenuButton>
			</Sidebar.MenuItem>
		</Sidebar.Menu>
	</Sidebar.Footer>

	<!-- Rail for collapse/expand -->
	<Sidebar.Rail />
</Sidebar.Root>
