// src/lib/components/layout/section-label.svelte
<script lang="ts">
	import type { Component, Snippet } from 'svelte';
	import { cn } from '$lib/utils.js';

	interface Props {
		title?: string;
		icon?: Component;
		iconClass?: string;
		class?: string;
		children?: Snippet;
	}

	let {
		title,
		icon: Icon,
		iconClass = 'h-4 w-4 text-muted-foreground',
		class: className,
		children,
	}: Props = $props();
</script>

<h3 class={cn('mb-2 flex items-center gap-2 text-sm font-medium', className)}>
	{#if Icon}
		<Icon class={iconClass} />
	{/if}
	{#if title}
		{title}
	{/if}
	{@render children?.()}
</h3>

// src/lib/components/layout/section-label.tsx
import type { ComponentType, ReactNode, SVGProps } from 'react';

import { cn } from '@/lib/utils';

export function SectionLabel({
	title,
	icon: Icon,
	iconClass = 'h-4 w-4 text-muted-foreground',
	className,
	children,
}: SectionLabelProps) {
	return (
		<h3 className={cn('mb-2 flex items-center gap-2 text-sm font-medium', className)}>
			{Icon ? <Icon className={iconClass} /> : null}
			{title}
			{children}
		</h3>
	);
}

export type SectionLabelProps = {
	readonly title?: string;
	readonly icon?: ComponentType<SVGProps<SVGSVGElement>>;
	readonly iconClass?: string;
	readonly className?: string;
	readonly children?: ReactNode;
};
